/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package ipc_practica1_grupo42_vista;

/**
 *
 * @author tomip
 */
public class GestorTareas extends javax.swing.JFrame {

    /**
     * Creates new form GestorTareas
     */
    public GestorTareas() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jSpinner1 = new javax.swing.JSpinner();
        jPanel1 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        jPanel5 = new javax.swing.JPanel();
        jPanel19 = new javax.swing.JPanel();
        anadirNombreTareaLabel = new javax.swing.JLabel();
        jPanel20 = new javax.swing.JPanel();
        anadirNombreTareaTextField = new javax.swing.JTextField();
        jPanel6 = new javax.swing.JPanel();
        jPanel21 = new javax.swing.JPanel();
        descripcionLabel = new javax.swing.JLabel();
        jPanel22 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        jPanel4 = new javax.swing.JPanel();
        jPanel7 = new javax.swing.JPanel();
        jPanel17 = new javax.swing.JPanel();
        fechaLabel = new javax.swing.JLabel();
        fechaFormattedTextField = new javax.swing.JFormattedTextField();
        jPanel18 = new javax.swing.JPanel();
        porcentajeLabel = new javax.swing.JLabel();
        porcentajeSpinner = new javax.swing.JSpinner();
        jPanel8 = new javax.swing.JPanel();
        prioridadLabel = new javax.swing.JLabel();
        prioridadComboBox = new javax.swing.JComboBox<>();
        completadoCheckBox = new javax.swing.JCheckBox();
        jPanel9 = new javax.swing.JPanel();
        guardarButton = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jPanel10 = new javax.swing.JPanel();
        verListaTextField = new javax.swing.JTextField();
        jPanel11 = new javax.swing.JPanel();
        jPanel12 = new javax.swing.JPanel();
        verNombreTareaLabel = new javax.swing.JLabel();
        jPanel13 = new javax.swing.JPanel();
        verTareaDescripcionLabel = new javax.swing.JLabel();
        jPanel14 = new javax.swing.JPanel();
        verFechaNoModificableLabel = new javax.swing.JLabel();
        verFechaModificableLabel = new javax.swing.JLabel();
        jPanel15 = new javax.swing.JPanel();
        verPrioridadNoModificableLabel = new javax.swing.JLabel();
        verPrioridadModificableLabel = new javax.swing.JLabel();
        verProgresoProgressBar = new javax.swing.JProgressBar();
        jPanel16 = new javax.swing.JPanel();
        editarButton = new javax.swing.JButton();
        eliminarButton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setLayout(new java.awt.GridLayout(2, 0));

        jPanel3.setLayout(new java.awt.GridLayout(2, 0));

        jPanel5.setLayout(new java.awt.GridLayout(1, 2));

        jPanel19.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.LEFT));

        anadirNombreTareaLabel.setText("Nombre de la tarea");
        anadirNombreTareaLabel.setHorizontalTextPosition(javax.swing.SwingConstants.LEFT);
        jPanel19.add(anadirNombreTareaLabel);

        jPanel5.add(jPanel19);

        anadirNombreTareaTextField.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        anadirNombreTareaTextField.setPreferredSize(new java.awt.Dimension(160, 22));
        anadirNombreTareaTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                anadirNombreTareaTextFieldActionPerformed(evt);
            }
        });
        jPanel20.add(anadirNombreTareaTextField);

        jPanel5.add(jPanel20);

        jPanel3.add(jPanel5);

        jPanel6.setLayout(new java.awt.GridLayout(1, 2));

        jPanel21.setMinimumSize(new java.awt.Dimension(25, 26));
        jPanel21.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.LEFT));

        descripcionLabel.setText("Descripción:");
        jPanel21.add(descripcionLabel);

        jPanel6.add(jPanel21);

        jPanel22.setLayout(new java.awt.BorderLayout());

        jTextArea1.setColumns(20);
        jTextArea1.setRows(5);
        jScrollPane1.setViewportView(jTextArea1);

        jPanel22.add(jScrollPane1, java.awt.BorderLayout.CENTER);

        jPanel6.add(jPanel22);

        jPanel3.add(jPanel6);

        jPanel1.add(jPanel3);

        jPanel4.setLayout(new java.awt.GridLayout(3, 0));

        jPanel7.setLayout(new java.awt.GridLayout(1, 2));

        jPanel17.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.LEFT));

        fechaLabel.setText("Fecha: ");
        jPanel17.add(fechaLabel);

        fechaFormattedTextField.setAutoscrolls(false);
        fechaFormattedTextField.setMinimumSize(new java.awt.Dimension(164, 22));
        fechaFormattedTextField.setPreferredSize(new java.awt.Dimension(164, 22));
        jPanel17.add(fechaFormattedTextField);

        jPanel7.add(jPanel17);

        jPanel18.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.LEFT));

        porcentajeLabel.setText("Porcentaje");
        jPanel18.add(porcentajeLabel);

        porcentajeSpinner.setMinimumSize(new java.awt.Dimension(60, 22));
        porcentajeSpinner.setName(""); // NOI18N
        porcentajeSpinner.setPreferredSize(new java.awt.Dimension(60, 22));
        jPanel18.add(porcentajeSpinner);

        jPanel7.add(jPanel18);

        jPanel4.add(jPanel7);

        jPanel8.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.LEFT));

        prioridadLabel.setText("Prioridad");
        jPanel8.add(prioridadLabel);

        prioridadComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Baja", "Media", "Alta" }));
        prioridadComboBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                prioridadComboBoxActionPerformed(evt);
            }
        });
        jPanel8.add(prioridadComboBox);

        completadoCheckBox.setText("Completado");
        completadoCheckBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                completadoCheckBoxActionPerformed(evt);
            }
        });
        jPanel8.add(completadoCheckBox);

        jPanel4.add(jPanel8);

        jPanel9.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.LEFT));

        guardarButton.setText("Guardar");
        guardarButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                guardarButtonActionPerformed(evt);
            }
        });
        jPanel9.add(guardarButton);

        jPanel4.add(jPanel9);

        jPanel1.add(jPanel4);

        getContentPane().add(jPanel1, java.awt.BorderLayout.LINE_START);

        jPanel2.setLayout(new java.awt.GridLayout(2, 0));

        verListaTextField.setEditable(false);
        verListaTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                verListaTextFieldActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel10Layout = new javax.swing.GroupLayout(jPanel10);
        jPanel10.setLayout(jPanel10Layout);
        jPanel10Layout.setHorizontalGroup(
            jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel10Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(verListaTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(167, Short.MAX_VALUE))
        );
        jPanel10Layout.setVerticalGroup(
            jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel10Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(verListaTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(275, Short.MAX_VALUE))
        );

        jPanel2.add(jPanel10);

        jPanel11.setLayout(new java.awt.GridLayout(5, 0));

        javax.swing.GroupLayout jPanel12Layout = new javax.swing.GroupLayout(jPanel12);
        jPanel12.setLayout(jPanel12Layout);
        jPanel12Layout.setHorizontalGroup(
            jPanel12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel12Layout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addComponent(verNombreTareaLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(191, Short.MAX_VALUE))
        );
        jPanel12Layout.setVerticalGroup(
            jPanel12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel12Layout.createSequentialGroup()
                .addContainerGap(54, Short.MAX_VALUE)
                .addComponent(verNombreTareaLabel)
                .addContainerGap())
        );

        jPanel11.add(jPanel12);

        javax.swing.GroupLayout jPanel13Layout = new javax.swing.GroupLayout(jPanel13);
        jPanel13.setLayout(jPanel13Layout);
        jPanel13Layout.setHorizontalGroup(
            jPanel13Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel13Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(verTareaDescripcionLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(201, Short.MAX_VALUE))
        );
        jPanel13Layout.setVerticalGroup(
            jPanel13Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel13Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(verTareaDescripcionLabel)
                .addContainerGap(54, Short.MAX_VALUE))
        );

        jPanel11.add(jPanel13);

        verFechaNoModificableLabel.setText("Fecha");

        javax.swing.GroupLayout jPanel14Layout = new javax.swing.GroupLayout(jPanel14);
        jPanel14.setLayout(jPanel14Layout);
        jPanel14Layout.setHorizontalGroup(
            jPanel14Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel14Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(verFechaNoModificableLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(verFechaModificableLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(146, Short.MAX_VALUE))
        );
        jPanel14Layout.setVerticalGroup(
            jPanel14Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel14Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel14Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(verFechaNoModificableLabel)
                    .addComponent(verFechaModificableLabel))
                .addContainerGap(38, Short.MAX_VALUE))
        );

        jPanel11.add(jPanel14);

        verPrioridadNoModificableLabel.setText("Prioridad");

        javax.swing.GroupLayout jPanel15Layout = new javax.swing.GroupLayout(jPanel15);
        jPanel15.setLayout(jPanel15Layout);
        jPanel15Layout.setHorizontalGroup(
            jPanel15Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel15Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(verPrioridadNoModificableLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(verPrioridadModificableLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(verProgresoProgressBar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel15Layout.setVerticalGroup(
            jPanel15Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel15Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel15Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(verProgresoProgressBar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel15Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(verPrioridadNoModificableLabel)
                        .addComponent(verPrioridadModificableLabel)))
                .addContainerGap(38, Short.MAX_VALUE))
        );

        jPanel11.add(jPanel15);

        editarButton.setText("Editar");
        editarButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                editarButtonActionPerformed(evt);
            }
        });

        eliminarButton.setText("Eliminar");

        javax.swing.GroupLayout jPanel16Layout = new javax.swing.GroupLayout(jPanel16);
        jPanel16.setLayout(jPanel16Layout);
        jPanel16Layout.setHorizontalGroup(
            jPanel16Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel16Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(editarButton)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(eliminarButton)
                .addContainerGap(81, Short.MAX_VALUE))
        );
        jPanel16Layout.setVerticalGroup(
            jPanel16Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel16Layout.createSequentialGroup()
                .addGap(0, 37, Short.MAX_VALUE)
                .addGroup(jPanel16Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(editarButton)
                    .addComponent(eliminarButton)))
        );

        jPanel11.add(jPanel16);

        jPanel2.add(jPanel11);

        getContentPane().add(jPanel2, java.awt.BorderLayout.LINE_END);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void guardarButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_guardarButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_guardarButtonActionPerformed

    private void verListaTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_verListaTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_verListaTextFieldActionPerformed

    private void editarButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_editarButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_editarButtonActionPerformed

    private void prioridadComboBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_prioridadComboBoxActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_prioridadComboBoxActionPerformed

    private void completadoCheckBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_completadoCheckBoxActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_completadoCheckBoxActionPerformed

    private void anadirNombreTareaTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_anadirNombreTareaTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_anadirNombreTareaTextFieldActionPerformed

    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel anadirNombreTareaLabel;
    private javax.swing.JTextField anadirNombreTareaTextField;
    private javax.swing.JCheckBox completadoCheckBox;
    private javax.swing.JLabel descripcionLabel;
    private javax.swing.JButton editarButton;
    private javax.swing.JButton eliminarButton;
    private javax.swing.JFormattedTextField fechaFormattedTextField;
    private javax.swing.JLabel fechaLabel;
    private javax.swing.JButton guardarButton;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel10;
    private javax.swing.JPanel jPanel11;
    private javax.swing.JPanel jPanel12;
    private javax.swing.JPanel jPanel13;
    private javax.swing.JPanel jPanel14;
    private javax.swing.JPanel jPanel15;
    private javax.swing.JPanel jPanel16;
    private javax.swing.JPanel jPanel17;
    private javax.swing.JPanel jPanel18;
    private javax.swing.JPanel jPanel19;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel20;
    private javax.swing.JPanel jPanel21;
    private javax.swing.JPanel jPanel22;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JPanel jPanel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSpinner jSpinner1;
    private javax.swing.JTextArea jTextArea1;
    private javax.swing.JLabel porcentajeLabel;
    private javax.swing.JSpinner porcentajeSpinner;
    private javax.swing.JComboBox<String> prioridadComboBox;
    private javax.swing.JLabel prioridadLabel;
    private javax.swing.JLabel verFechaModificableLabel;
    private javax.swing.JLabel verFechaNoModificableLabel;
    private javax.swing.JTextField verListaTextField;
    private javax.swing.JLabel verNombreTareaLabel;
    private javax.swing.JLabel verPrioridadModificableLabel;
    private javax.swing.JLabel verPrioridadNoModificableLabel;
    private javax.swing.JProgressBar verProgresoProgressBar;
    private javax.swing.JLabel verTareaDescripcionLabel;
    // End of variables declaration//GEN-END:variables
}
