/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package uva.ipc.practica2.vista;

import java.util.Date;
import uva.ipc.practica2.modelo.ListaTareas;
import uva.ipc.practica2.modelo.Tarea;
import java.text.SimpleDateFormat;
import java.util.ArrayList;
import javax.swing.DefaultComboBoxModel;
import javax.swing.ListSelectionModel;

/**
 * Clase que modifica y controla todo lo relacionado con la vista
 * 
 * @author tomruiz, irereto
 */
public class VistaGestorTareas extends javax.swing.JFrame {

    private ControladorGestorTareas controlador;

     /**
     * Inicializador de la vista
     */
    public VistaGestorTareas() {
        initComponents();
        this.controlador = new ControladorGestorTareas(this);
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        jPanel1 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        anadirNombreTareaLabel = new javax.swing.JLabel();
        anadirNombreTareaTextField = new javax.swing.JTextField();
        descripcionLabel = new javax.swing.JLabel();
        descripcionScrollPane = new javax.swing.JScrollPane();
        descripcionTextArea = new javax.swing.JTextArea();
        jPanel4 = new javax.swing.JPanel();
        fechaLabel = new javax.swing.JLabel();
        fechaDateChooser = new com.toedter.calendar.JDateChooser();
        prioridadLabel = new javax.swing.JLabel();
        prioridadComboBox = new javax.swing.JComboBox<>();
        anadirProgresoLabel = new javax.swing.JLabel();
        porcentajeSpinner = new javax.swing.JSpinner();
        listaActualLabel = new javax.swing.JLabel();
        seleccionarListaComboBox = new javax.swing.JComboBox<>();
        completadoCheckBox = new javax.swing.JCheckBox();
        jPanel5 = new javax.swing.JPanel();
        erroresLabel = new javax.swing.JLabel();
        jPanel9 = new javax.swing.JPanel();
        guardarButton = new javax.swing.JButton();
        limpiarButton = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jPanel10 = new javax.swing.JPanel();
        listaTareasScrollPane = new javax.swing.JScrollPane();
        listaTareasList = new javax.swing.JList<>();
        jPanel11 = new javax.swing.JPanel();
        jPanel12 = new javax.swing.JPanel();
        verNombreTareaLabel = new javax.swing.JLabel();
        verNombreTareaNoModificableLabel = new javax.swing.JLabel();
        jPanel13 = new javax.swing.JPanel();
        verDescripcionJSCroll = new javax.swing.JScrollPane();
        verDescripcionTextArea = new javax.swing.JTextArea();
        verDescripcionNoModificableLabel = new javax.swing.JLabel();
        jPanel14 = new javax.swing.JPanel();
        verFechaNoModificableLabel = new javax.swing.JLabel();
        verFechaModificableLabel = new javax.swing.JLabel();
        verListaNoModificableLabel = new javax.swing.JLabel();
        verListaModificableLabel = new javax.swing.JLabel();
        verPrioridadNoModificableLabel = new javax.swing.JLabel();
        verPrioridadModificableLabel = new javax.swing.JLabel();
        verProgresoLabel = new javax.swing.JLabel();
        verProgresoNumeroNoModificableLabel = new javax.swing.JLabel();
        verProgresoProgressBar = new javax.swing.JProgressBar();
        jPanel16 = new javax.swing.JPanel();
        editarButton = new javax.swing.JButton();
        eliminarButton = new javax.swing.JButton();
        jPanel26 = new javax.swing.JPanel();
        GestorListasButton = new javax.swing.JButton();
        jPanel32 = new javax.swing.JPanel();
        jPanel31 = new javax.swing.JPanel();
        MenuButton = new javax.swing.JButton();
        jPanel35 = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(255, 255, 204));
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        setMinimumSize(new java.awt.Dimension(1150, 700));
        setPreferredSize(new java.awt.Dimension(1500, 800));
        getContentPane().setLayout(new java.awt.GridBagLayout());

        jPanel1.setBackground(new java.awt.Color(255, 255, 204));
        jPanel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel1.setMinimumSize(new java.awt.Dimension(100, 50));
        jPanel1.setName(""); // NOI18N
        jPanel1.setPreferredSize(new java.awt.Dimension(750, 860));
        jPanel1.setLayout(new java.awt.GridBagLayout());

        jPanel3.setBackground(new java.awt.Color(255, 255, 204));
        jPanel3.setMinimumSize(new java.awt.Dimension(75, 86));
        jPanel3.setName(""); // NOI18N
        jPanel3.setLayout(new java.awt.GridBagLayout());

        anadirNombreTareaLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        anadirNombreTareaLabel.setText("Nombre de la tarea");
        anadirNombreTareaLabel.setHorizontalTextPosition(javax.swing.SwingConstants.LEFT);
        anadirNombreTareaLabel.setMaximumSize(new java.awt.Dimension(65, 16));
        anadirNombreTareaLabel.setMinimumSize(new java.awt.Dimension(65, 16));
        anadirNombreTareaLabel.setPreferredSize(new java.awt.Dimension(65, 16));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.weightx = 0.3;
        gridBagConstraints.weighty = 0.3;
        jPanel3.add(anadirNombreTareaLabel, gridBagConstraints);

        anadirNombreTareaTextField.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        anadirNombreTareaTextField.setMaximumSize(new java.awt.Dimension(2147483647, 32));
        anadirNombreTareaTextField.setMinimumSize(new java.awt.Dimension(64, 32));
        anadirNombreTareaTextField.setName(""); // NOI18N
        anadirNombreTareaTextField.setNextFocusableComponent(descripcionTextArea);
        anadirNombreTareaTextField.setPreferredSize(new java.awt.Dimension(450, 32));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.weightx = 0.7;
        gridBagConstraints.weighty = 0.3;
        jPanel3.add(anadirNombreTareaTextField, gridBagConstraints);

        descripcionLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        descripcionLabel.setText("Descripción:");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.weightx = 0.3;
        gridBagConstraints.weighty = 0.7;
        jPanel3.add(descripcionLabel, gridBagConstraints);

        descripcionScrollPane.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_NEVER);
        descripcionScrollPane.setVerticalScrollBarPolicy(javax.swing.ScrollPaneConstants.VERTICAL_SCROLLBAR_ALWAYS);
        descripcionScrollPane.setHorizontalScrollBar(null);
        descripcionScrollPane.setPreferredSize(new java.awt.Dimension(144, 86));

        descripcionTextArea.setColumns(20);
        descripcionTextArea.setLineWrap(true);
        descripcionTextArea.setRows(5);
        descripcionTextArea.setToolTipText("");
        descripcionTextArea.setWrapStyleWord(true);
        descripcionTextArea.setName(""); // NOI18N
        descripcionTextArea.setNextFocusableComponent(fechaDateChooser);
        descripcionTextArea.setPreferredSize(new java.awt.Dimension(450, 74));
        descripcionScrollPane.setViewportView(descripcionTextArea);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.weightx = 0.7;
        gridBagConstraints.weighty = 0.7;
        jPanel3.add(descripcionScrollPane, gridBagConstraints);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.weighty = 0.5;
        gridBagConstraints.insets = new java.awt.Insets(10, 10, 10, 10);
        jPanel1.add(jPanel3, gridBagConstraints);

        jPanel4.setBackground(new java.awt.Color(255, 255, 204));
        jPanel4.setMinimumSize(new java.awt.Dimension(75, 86));
        jPanel4.setName(""); // NOI18N
        jPanel4.setPreferredSize(new java.awt.Dimension(280, 86));
        jPanel4.setLayout(new java.awt.GridBagLayout());

        fechaLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        fechaLabel.setText("Fecha: ");
        fechaLabel.setMinimumSize(new java.awt.Dimension(20, 16));
        fechaLabel.setPreferredSize(new java.awt.Dimension(20, 16));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.weightx = 0.2;
        gridBagConstraints.weighty = 0.25;
        jPanel4.add(fechaLabel, gridBagConstraints);

        fechaDateChooser.setBackground(new java.awt.Color(255, 255, 204));
        fechaDateChooser.setDate(java.sql.Date.valueOf(java.time.LocalDate.now()));
        fechaDateChooser.setDateFormatString("dd/MM/yyyy");
        fechaDateChooser.setMaxSelectableDate(new java.util.Date(253370764872000L));
        fechaDateChooser.setMinimumSize(new java.awt.Dimension(35, 28));
        fechaDateChooser.setNextFocusableComponent(prioridadComboBox);
        fechaDateChooser.setPreferredSize(new java.awt.Dimension(35, 28));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.weightx = 0.2;
        gridBagConstraints.weighty = 0.25;
        jPanel4.add(fechaDateChooser, gridBagConstraints);

        prioridadLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        prioridadLabel.setText("Prioridad:");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 4;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.weightx = 0.1;
        gridBagConstraints.weighty = 0.25;
        jPanel4.add(prioridadLabel, gridBagConstraints);

        prioridadComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Baja", "Media", "Alta" }));
        prioridadComboBox.setMinimumSize(new java.awt.Dimension(35, 28));
        prioridadComboBox.setName(""); // NOI18N
        prioridadComboBox.setNextFocusableComponent(porcentajeSpinner);
        prioridadComboBox.setPreferredSize(new java.awt.Dimension(35, 28));
        prioridadComboBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                prioridadComboBoxActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 5;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.weightx = 0.2;
        gridBagConstraints.weighty = 0.25;
        gridBagConstraints.insets = new java.awt.Insets(0, 0, 0, 20);
        jPanel4.add(prioridadComboBox, gridBagConstraints);

        anadirProgresoLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        anadirProgresoLabel.setText("Progreso:");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.weightx = 0.2;
        gridBagConstraints.weighty = 0.25;
        jPanel4.add(anadirProgresoLabel, gridBagConstraints);

        porcentajeSpinner.setModel(new javax.swing.SpinnerNumberModel(0, 0, 100, 1));
        porcentajeSpinner.setMinimumSize(new java.awt.Dimension(35, 28));
        porcentajeSpinner.setName(""); // NOI18N
        porcentajeSpinner.setNextFocusableComponent(completadoCheckBox);
        porcentajeSpinner.setPreferredSize(new java.awt.Dimension(35, 28));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.weightx = 0.2;
        gridBagConstraints.weighty = 0.25;
        jPanel4.add(porcentajeSpinner, gridBagConstraints);

        listaActualLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        listaActualLabel.setText("Lista:");
        listaActualLabel.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 4;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.weightx = 0.2;
        gridBagConstraints.weighty = 0.25;
        jPanel4.add(listaActualLabel, gridBagConstraints);

        seleccionarListaComboBox.setMinimumSize(new java.awt.Dimension(35, 28));
        seleccionarListaComboBox.setPreferredSize(new java.awt.Dimension(35, 28));
        seleccionarListaComboBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                seleccionarListaComboBoxActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 5;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.weightx = 0.2;
        gridBagConstraints.weighty = 0.25;
        gridBagConstraints.insets = new java.awt.Insets(0, 0, 0, 20);
        jPanel4.add(seleccionarListaComboBox, gridBagConstraints);

        completadoCheckBox.setBackground(new java.awt.Color(255, 255, 204));
        completadoCheckBox.setText("Completado");
        completadoCheckBox.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        completadoCheckBox.setNextFocusableComponent(guardarButton);
        completadoCheckBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                completadoCheckBoxActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 3;
        gridBagConstraints.gridy = 3;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.weighty = 0.25;
        jPanel4.add(completadoCheckBox, gridBagConstraints);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.weighty = 0.3;
        gridBagConstraints.insets = new java.awt.Insets(0, 10, 0, 10);
        jPanel1.add(jPanel4, gridBagConstraints);

        jPanel5.setBackground(new java.awt.Color(255, 255, 204));
        jPanel5.setMinimumSize(new java.awt.Dimension(75, 22));
        jPanel5.setPreferredSize(new java.awt.Dimension(75, 22));
        jPanel5.setLayout(new java.awt.GridBagLayout());

        erroresLabel.setBackground(new java.awt.Color(255, 255, 204));
        erroresLabel.setFont(new java.awt.Font("Liberation Sans", 1, 12)); // NOI18N
        erroresLabel.setForeground(new java.awt.Color(153, 0, 51));
        erroresLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        erroresLabel.setAlignmentX(0.5F);
        erroresLabel.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.ipadx = 75;
        gridBagConstraints.ipady = 23;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        jPanel5.add(erroresLabel, gridBagConstraints);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 3;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.weighty = 0.1;
        gridBagConstraints.insets = new java.awt.Insets(0, 10, 0, 10);
        jPanel1.add(jPanel5, gridBagConstraints);

        jPanel9.setBackground(new java.awt.Color(255, 255, 204));
        jPanel9.setMinimumSize(new java.awt.Dimension(75, 33));
        jPanel9.setName(""); // NOI18N
        jPanel9.setPreferredSize(new java.awt.Dimension(550, 33));
        jPanel9.setLayout(new java.awt.GridBagLayout());

        guardarButton.setBackground(new java.awt.Color(255, 153, 0));
        guardarButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/uva/ipc/practica2/vista/guardar.png"))); // NOI18N
        guardarButton.setText("Guardar");
        guardarButton.setMinimumSize(new java.awt.Dimension(82, 28));
        guardarButton.setPreferredSize(new java.awt.Dimension(87, 35));
        guardarButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                guardarButtonActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.weightx = 0.3;
        gridBagConstraints.weighty = 1.0;
        gridBagConstraints.insets = new java.awt.Insets(0, 0, 0, 10);
        jPanel9.add(guardarButton, gridBagConstraints);

        limpiarButton.setBackground(new java.awt.Color(255, 153, 0));
        limpiarButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/uva/ipc/practica2/vista/escoba.png"))); // NOI18N
        limpiarButton.setText("Limpiar");
        limpiarButton.setPreferredSize(new java.awt.Dimension(82, 35));
        limpiarButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                limpiarButtonActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.weightx = 0.3;
        gridBagConstraints.weighty = 1.0;
        gridBagConstraints.insets = new java.awt.Insets(0, 10, 0, 0);
        jPanel9.add(limpiarButton, gridBagConstraints);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 4;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.weighty = 0.1;
        gridBagConstraints.insets = new java.awt.Insets(10, 10, 10, 10);
        jPanel1.add(jPanel9, gridBagConstraints);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.weightx = 0.5;
        gridBagConstraints.weighty = 0.95;
        gridBagConstraints.insets = new java.awt.Insets(10, 10, 10, 10);
        getContentPane().add(jPanel1, gridBagConstraints);

        jPanel2.setBackground(new java.awt.Color(255, 255, 204));
        jPanel2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel2.setMinimumSize(new java.awt.Dimension(75, 86));
        jPanel2.setPreferredSize(new java.awt.Dimension(750, 860));
        jPanel2.setLayout(new java.awt.GridBagLayout());

        jPanel10.setBackground(new java.awt.Color(255, 255, 204));
        jPanel10.setMinimumSize(new java.awt.Dimension(75, 86));
        jPanel10.setPreferredSize(new java.awt.Dimension(515, 86));
        jPanel10.setLayout(new java.awt.GridBagLayout());

        listaTareasScrollPane.setBackground(new java.awt.Color(255, 255, 204));

        listaTareasList.setSelectionMode(ListSelectionModel.SINGLE_SELECTION);
        listaTareasList.addListSelectionListener(new javax.swing.event.ListSelectionListener() {
            public void valueChanged(javax.swing.event.ListSelectionEvent evt) {
                listaTareasListValueChanged(evt);
            }
        });
        listaTareasScrollPane.setViewportView(listaTareasList);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.weighty = 1.0;
        jPanel10.add(listaTareasScrollPane, gridBagConstraints);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.weighty = 0.5;
        gridBagConstraints.insets = new java.awt.Insets(10, 10, 10, 10);
        jPanel2.add(jPanel10, gridBagConstraints);

        jPanel11.setBackground(new java.awt.Color(255, 255, 204));
        jPanel11.setBorder(javax.swing.BorderFactory.createTitledBorder(""));
        jPanel11.setMinimumSize(new java.awt.Dimension(75, 108));
        jPanel11.setPreferredSize(new java.awt.Dimension(269, 108));
        jPanel11.setLayout(new java.awt.GridBagLayout());

        jPanel12.setBackground(new java.awt.Color(255, 255, 204));
        jPanel12.setMinimumSize(new java.awt.Dimension(50, 28));
        jPanel12.setPreferredSize(new java.awt.Dimension(50, 28));
        jPanel12.setLayout(new java.awt.GridBagLayout());

        verNombreTareaLabel.setBackground(new java.awt.Color(255, 255, 255));
        verNombreTareaLabel.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        verNombreTareaLabel.setHorizontalTextPosition(javax.swing.SwingConstants.LEFT);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.weightx = 0.9;
        gridBagConstraints.weighty = 1.0;
        jPanel12.add(verNombreTareaLabel, gridBagConstraints);

        verNombreTareaNoModificableLabel.setBackground(new java.awt.Color(255, 255, 255));
        verNombreTareaNoModificableLabel.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        verNombreTareaNoModificableLabel.setText("Nombre:");
        verNombreTareaNoModificableLabel.setMaximumSize(new java.awt.Dimension(35, 16));
        verNombreTareaNoModificableLabel.setMinimumSize(new java.awt.Dimension(35, 16));
        verNombreTareaNoModificableLabel.setPreferredSize(new java.awt.Dimension(35, 16));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.weightx = 0.1;
        gridBagConstraints.weighty = 1.0;
        jPanel12.add(verNombreTareaNoModificableLabel, gridBagConstraints);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.weighty = 0.2;
        gridBagConstraints.insets = new java.awt.Insets(10, 10, 10, 10);
        jPanel11.add(jPanel12, gridBagConstraints);

        jPanel13.setBackground(new java.awt.Color(255, 255, 204));
        jPanel13.setLayout(new java.awt.GridBagLayout());

        verDescripcionJSCroll.setBackground(new java.awt.Color(255, 153, 255));
        verDescripcionJSCroll.setEnabled(false);

        verDescripcionTextArea.setEditable(false);
        verDescripcionTextArea.setBackground(new java.awt.Color(255, 153, 255));
        verDescripcionTextArea.setColumns(20);
        verDescripcionTextArea.setRows(5);
        verDescripcionTextArea.setAutoscrolls(false);
        verDescripcionTextArea.setOpaque(false);
        verDescripcionJSCroll.setViewportView(verDescripcionTextArea);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.weighty = 0.9;
        jPanel13.add(verDescripcionJSCroll, gridBagConstraints);

        verDescripcionNoModificableLabel.setBackground(new java.awt.Color(255, 153, 255));
        verDescripcionNoModificableLabel.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        verDescripcionNoModificableLabel.setText("Descripción:");
        verDescripcionNoModificableLabel.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.weighty = 0.1;
        jPanel13.add(verDescripcionNoModificableLabel, gridBagConstraints);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.weighty = 0.2;
        gridBagConstraints.insets = new java.awt.Insets(10, 10, 10, 10);
        jPanel11.add(jPanel13, gridBagConstraints);

        jPanel14.setBackground(new java.awt.Color(255, 255, 204));
        jPanel14.setMinimumSize(new java.awt.Dimension(50, 28));
        jPanel14.setPreferredSize(new java.awt.Dimension(50, 28));
        jPanel14.setLayout(new java.awt.GridBagLayout());

        verFechaNoModificableLabel.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        verFechaNoModificableLabel.setText("Fecha:");
        verFechaNoModificableLabel.setMaximumSize(new java.awt.Dimension(35, 16));
        verFechaNoModificableLabel.setMinimumSize(new java.awt.Dimension(35, 16));
        verFechaNoModificableLabel.setPreferredSize(new java.awt.Dimension(35, 16));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.weightx = 0.1;
        gridBagConstraints.weighty = 0.5;
        jPanel14.add(verFechaNoModificableLabel, gridBagConstraints);

        verFechaModificableLabel.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.weightx = 0.3;
        gridBagConstraints.weighty = 0.5;
        jPanel14.add(verFechaModificableLabel, gridBagConstraints);

        verListaNoModificableLabel.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        verListaNoModificableLabel.setText("Lista:");
        verListaNoModificableLabel.setMaximumSize(new java.awt.Dimension(35, 16));
        verListaNoModificableLabel.setMinimumSize(new java.awt.Dimension(35, 16));
        verListaNoModificableLabel.setPreferredSize(new java.awt.Dimension(35, 16));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 3;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.weightx = 0.1;
        gridBagConstraints.weighty = 0.5;
        jPanel14.add(verListaNoModificableLabel, gridBagConstraints);

        verListaModificableLabel.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 4;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.weightx = 0.5;
        gridBagConstraints.weighty = 0.5;
        jPanel14.add(verListaModificableLabel, gridBagConstraints);

        verPrioridadNoModificableLabel.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        verPrioridadNoModificableLabel.setText("Prioridad:");
        verPrioridadNoModificableLabel.setMaximumSize(new java.awt.Dimension(50, 16));
        verPrioridadNoModificableLabel.setMinimumSize(new java.awt.Dimension(35, 16));
        verPrioridadNoModificableLabel.setPreferredSize(new java.awt.Dimension(35, 16));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 3;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.weightx = 0.1;
        gridBagConstraints.weighty = 0.5;
        jPanel14.add(verPrioridadNoModificableLabel, gridBagConstraints);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 3;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.weightx = 0.3;
        gridBagConstraints.weighty = 0.5;
        jPanel14.add(verPrioridadModificableLabel, gridBagConstraints);

        verProgresoLabel.setBackground(new java.awt.Color(255, 255, 255));
        verProgresoLabel.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        verProgresoLabel.setText("Progreso:");
        verProgresoLabel.setMaximumSize(new java.awt.Dimension(35, 16));
        verProgresoLabel.setMinimumSize(new java.awt.Dimension(35, 16));
        verProgresoLabel.setPreferredSize(new java.awt.Dimension(35, 16));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 3;
        gridBagConstraints.gridy = 3;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.weightx = 0.1;
        gridBagConstraints.weighty = 0.5;
        jPanel14.add(verProgresoLabel, gridBagConstraints);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 4;
        gridBagConstraints.gridy = 3;
        gridBagConstraints.weightx = 0.6;
        gridBagConstraints.weighty = 0.5;
        jPanel14.add(verProgresoNumeroNoModificableLabel, gridBagConstraints);

        verProgresoProgressBar.setBackground(new java.awt.Color(255, 255, 255));
        verProgresoProgressBar.setForeground(new java.awt.Color(0, 204, 51));
        verProgresoProgressBar.setMaximumSize(new java.awt.Dimension(32767, 20));
        verProgresoProgressBar.setMinimumSize(new java.awt.Dimension(10, 20));
        verProgresoProgressBar.setPreferredSize(new java.awt.Dimension(146, 20));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 4;
        gridBagConstraints.gridy = 3;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.weightx = 0.5;
        gridBagConstraints.weighty = 0.5;
        jPanel14.add(verProgresoProgressBar, gridBagConstraints);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 3;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.weighty = 0.2;
        gridBagConstraints.insets = new java.awt.Insets(10, 10, 10, 10);
        jPanel11.add(jPanel14, gridBagConstraints);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.weighty = 0.4;
        gridBagConstraints.insets = new java.awt.Insets(0, 10, 0, 10);
        jPanel2.add(jPanel11, gridBagConstraints);

        jPanel16.setBackground(new java.awt.Color(255, 255, 204));
        jPanel16.setMinimumSize(new java.awt.Dimension(75, 33));
        jPanel16.setPreferredSize(new java.awt.Dimension(550, 33));
        jPanel16.setLayout(new java.awt.GridBagLayout());

        editarButton.setBackground(new java.awt.Color(255, 153, 0));
        editarButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/uva/ipc/practica2/vista/editar-pequeño.png"))); // NOI18N
        editarButton.setText("Editar");
        editarButton.setMinimumSize(new java.awt.Dimension(82, 28));
        editarButton.setPreferredSize(new java.awt.Dimension(82, 35));
        editarButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                editarButtonActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.weightx = 0.5;
        gridBagConstraints.weighty = 1.0;
        gridBagConstraints.insets = new java.awt.Insets(0, 0, 0, 10);
        jPanel16.add(editarButton, gridBagConstraints);

        eliminarButton.setBackground(new java.awt.Color(255, 153, 0));
        eliminarButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/uva/ipc/practica2/vista/eliminar.png"))); // NOI18N
        eliminarButton.setText("Eliminar");
        eliminarButton.setMinimumSize(new java.awt.Dimension(82, 28));
        eliminarButton.setPreferredSize(new java.awt.Dimension(82, 35));
        eliminarButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                eliminarButtonActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.weightx = 0.5;
        gridBagConstraints.weighty = 1.0;
        gridBagConstraints.insets = new java.awt.Insets(0, 10, 0, 0);
        jPanel16.add(eliminarButton, gridBagConstraints);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 3;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.weighty = 0.1;
        gridBagConstraints.insets = new java.awt.Insets(10, 10, 10, 10);
        jPanel2.add(jPanel16, gridBagConstraints);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.weightx = 0.5;
        gridBagConstraints.weighty = 0.95;
        gridBagConstraints.insets = new java.awt.Insets(10, 10, 10, 10);
        getContentPane().add(jPanel2, gridBagConstraints);

        jPanel26.setLayout(new java.awt.GridBagLayout());

        GestorListasButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/uva/ipc/practica2/vista/editar_listas.png"))); // NOI18N
        GestorListasButton.setText("Gestionar Listas");
        GestorListasButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                GestorListasButtonActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 4;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.weightx = 0.25;
        gridBagConstraints.weighty = 1.0;
        gridBagConstraints.insets = new java.awt.Insets(10, 10, 10, 10);
        jPanel26.add(GestorListasButton, gridBagConstraints);

        javax.swing.GroupLayout jPanel32Layout = new javax.swing.GroupLayout(jPanel32);
        jPanel32.setLayout(jPanel32Layout);
        jPanel32Layout.setHorizontalGroup(
            jPanel32Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        jPanel32Layout.setVerticalGroup(
            jPanel32Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.weightx = 0.75;
        gridBagConstraints.weighty = 1.0;
        jPanel26.add(jPanel32, gridBagConstraints);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.weightx = 0.5;
        gridBagConstraints.weighty = 0.05;
        gridBagConstraints.insets = new java.awt.Insets(10, 10, 10, 10);
        getContentPane().add(jPanel26, gridBagConstraints);

        jPanel31.setLayout(new java.awt.GridBagLayout());

        MenuButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/uva/ipc/practica2/vista/flecha_atras.png"))); // NOI18N
        MenuButton.setText("Menú Principal");
        MenuButton.setMaximumSize(new java.awt.Dimension(150, 41));
        MenuButton.setMinimumSize(new java.awt.Dimension(150, 41));
        MenuButton.setPreferredSize(new java.awt.Dimension(150, 41));
        MenuButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MenuButtonActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.weightx = 0.25;
        gridBagConstraints.weighty = 1.0;
        gridBagConstraints.insets = new java.awt.Insets(10, 10, 10, 10);
        jPanel31.add(MenuButton, gridBagConstraints);

        javax.swing.GroupLayout jPanel35Layout = new javax.swing.GroupLayout(jPanel35);
        jPanel35.setLayout(jPanel35Layout);
        jPanel35Layout.setHorizontalGroup(
            jPanel35Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        jPanel35Layout.setVerticalGroup(
            jPanel35Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.weightx = 0.75;
        gridBagConstraints.weighty = 1.0;
        jPanel31.add(jPanel35, gridBagConstraints);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.weightx = 0.5;
        gridBagConstraints.weighty = 0.05;
        gridBagConstraints.insets = new java.awt.Insets(10, 10, 10, 10);
        getContentPane().add(jPanel31, gridBagConstraints);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * Funcion que maneja el evento de seleccionar el boton de guardar.
     * Llama al controlador para que procese el evento
     * 
     * @param evt: evento de accion generado por el click del boton
     */
    private void guardarButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_guardarButtonActionPerformed
        // TODO add your handling code here:
        controlador.procesarEventoGuardar();
    }//GEN-LAST:event_guardarButtonActionPerformed

    
    /**
     * Funcion que maneja el evento de seleccionar el boton de editar.
     * Llama al controlador para que procese el evento
     * 
     * @param evt: evento de accion generado por el click del boton
     */
    private void editarButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_editarButtonActionPerformed
        // TODO add your handling code here:
        controlador.procesarEventoEditar();
    }//GEN-LAST:event_editarButtonActionPerformed

    /**
     * Funcion que maneja el evento de seleccionar una tarea de la lista.
     * Llama al controlador para que procese el evento
     * 
     * @param evt: evento de cambio de seleccion generado por la lista
     */
    private void listaTareasListValueChanged(javax.swing.event.ListSelectionEvent evt) {//GEN-FIRST:event_listaTareasListValueChanged
        // TODO add your handling code here:
        controlador.procesarEventoSeleccionarTarea(listaTareasList.getSelectedValue());
        erroresLabel.setText("");
    }//GEN-LAST:event_listaTareasListValueChanged

    /**
     * Funcion que maneja el evento de seleccionar el boton de eliminar.
     * Llama al controlador para que procese el evento
     * 
     * @param evt: evento de accion generado por el click del boton
     */
    private void eliminarButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_eliminarButtonActionPerformed
        // TODO add your handling code here:
        controlador.procesarEventoEliminar();
    }//GEN-LAST:event_eliminarButtonActionPerformed

    /**
     * Funcion que maneja el evento de seleccionar el boton de limpiar.
     * Llama al controlador para que procese el evento
     * 
     * @param evt: evento de accion generado por el click del boton
     */
    private void limpiarButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_limpiarButtonActionPerformed
        // TODO add your handling code here:
        controlador.procesarEventoLimpiar();
    }//GEN-LAST:event_limpiarButtonActionPerformed

    /**
     * Funcion que maneja el evento de marcar o desmarcar el checkbox.
     * Llama al controlador para que procese el evento
     * 
     * @param evt: evento de accion generado por la interaccion con el checkbox
     */
    private void completadoCheckBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_completadoCheckBoxActionPerformed
        // TODO add your handling code here:
        controlador.procesarEventoCompletado();
        
    }//GEN-LAST:event_completadoCheckBoxActionPerformed

    private void prioridadComboBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_prioridadComboBoxActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_prioridadComboBoxActionPerformed

    private void seleccionarListaComboBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_seleccionarListaComboBoxActionPerformed
        // TODO add your handling code here:
        controlador.procesarCambiarListaSeleccionada();
    }//GEN-LAST:event_seleccionarListaComboBoxActionPerformed

    private void GestorListasButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_GestorListasButtonActionPerformed
        // TODO add your handling code here:
        controlador.procesarEventoVistaListas();
    }//GEN-LAST:event_GestorListasButtonActionPerformed

    private void MenuButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MenuButtonActionPerformed
        // TODO add your handling code here:
        controlador.procesarEventoVistaMenu();
    }//GEN-LAST:event_MenuButtonActionPerformed

    /**
     * Funcion que actualiza la lista de tareas que se muestran.
     * Convierte el ArrayList de tareas un array de String
     * 
     * @param tareas: ArrayList de tareas que tiene que mostrar la lista
     */
    public void actualizarTareas(ArrayList<Tarea> tareas) {
         String[] tareasArray = new String[tareas.size()];
    
        for (int i = 0; i < tareas.size(); i++) {
            tareasArray[i] = tareas.get(i).toString();
        }
        listaTareasList.setListData(tareasArray);
    }
    /**
     * Funcion que actualiza la lista de listas en el desplegable seleccionarLista que se muestran.
     * Convierte el ArrayList de listas en un array de String
     * 
     * @param listas: ArrayList de listas que tiene que mostrar la lista
     */
    public void actualizarListas(ArrayList<ListaTareas> listas) {
        String[] listasArray = new String[listas.size()];
    
        for (int i = 0; i < listas.size(); i++) {
            listasArray[i] = listas.get(i).getNombre();
        }
        seleccionarListaComboBox.setModel(new DefaultComboBoxModel <> (listasArray));
    }
    

    /**
     * Funcion que cambia el texto de los campos no modificables con la informacion
     * de una tarea
     * 
     * @param t: tarea de la cual se quiere mostrar la informacion
     */
    public void cambiarCamposNoModificables(Tarea t){
        SimpleDateFormat formato = new SimpleDateFormat("dd/MM/yyyy");
        verNombreTareaLabel.setText(t.getNombreTarea());
        verDescripcionTextArea.setText(t.getDescripcionTareas());
        verFechaModificableLabel.setText(formato.format(t.getFecha()));
        verPrioridadModificableLabel.setText(t.getPrioridad());
        verProgresoProgressBar.setValue(t.getProgreso());
        verProgresoNumeroNoModificableLabel.setText(Integer.toString(t.getProgreso()));
    }
    
   
    /**
     * Funcion que devuelve el nombre de la tarea ingresada por el usuario
     * 
     * @return el nombre de la tarea
     */
    public String getNombreTarea() {
        return anadirNombreTareaTextField.getText();
    }

    
    /**
     * Funcion que devuelve la descripcion de la tarea ingresada por el usuario
     * 
     * @return la descripcion de la tarea
     */
    public String getDescripcion() {
        return descripcionTextArea.getText();
    }

    /**
     * Funcion que devuelve la fecja de la tarea ingresada por el usuario
     * 
     * @return la fecha de la tarea
     */
    public Date getFecha() {
        Date fecha = (Date) fechaDateChooser.getDate();
        return fecha;
    }

    /**
     * Funcion que devuelve la prioridad de la tarea ingresada por el usuario
     * 
     * @return la prioridad de la tarea
     */
    public String getPrioridad() {
        return (String) prioridadComboBox.getSelectedItem();
    }

    /**
     * Funcion que devuelve el progreso de la tarea ingresada por el usuario
     * 
     * @return el progreso de la tarea
     */
    public int getProgreso() {
        return (int) porcentajeSpinner.getValue();
    }

    /**
     * Funcion que devuelve si la tarea ingresada por el usuario esta completada
     * 
     * @return si la tarea esta completada o no en un boolean
     */
    public boolean getCompletado() {
        return completadoCheckBox.isSelected();
    }
    
    /**
     * Funcion que devuelve la tarea seleccionada de la lista
     * 
     * @return la tarea seleccionada
     */
    public String getTareaSeleccionada(){
        return listaTareasList.getSelectedValue();
    }
    
    
    public int getListaSeleccionada(){
        return seleccionarListaComboBox.getSelectedIndex();
    }
    
    
    
    
    
    /**
     * Setter del campo de texto del nombre de la tarea.
     * No es necesario comprobar que no recibe un null porque cuando es llamada ya se ha comprobado que los atributos de la tarea son correctos
     * 
     * @param nombreTarea: String que se refiere al nombre de la tarea
     */
    public void setNombreTarea(String nombreTarea) {
        anadirNombreTareaTextField.setText(nombreTarea);
    }

    /**
     * Setter del area de texto de la descripcion de la tarea.
     * No es necesario comprobar que no recibe un null porque cuando es llamada ya se ha comprobado que los atributos de la tarea son correctos
     * 
     * @param descripcion: String que se refiere a la descripcion de la tarea
     */
    public void setDescripcion(String descripcion) {
        descripcionTextArea.setText(descripcion);
    }

    /**
     * Setter del dateChooser de la fecha de la tarea.
     * No es necesario comprobar que no recibe un null porque cuando es llamada ya se ha comprobado que los atributos de la tarea son correctos
     * 
     * @param fecha: Date que se refiere a la fecha de la tarea
     */
    public void setFecha(Date fecha) {
        fechaDateChooser.setDate(fecha);
    }

    /**
     * Setter del ComboBox de la prioridad de la tarea.
     * No es necesario comprobar que no recibe un null porque cuando es llamada ya se ha comprobado que los atributos de la tarea son correctos
     * 
     * @param prioridad: String que se refiere a la prioridad de la tarea
     */
    public void setPrioridad(String prioridad) {
        prioridadComboBox.setSelectedItem(prioridad);
    }

    /**
     * Setter del Spinner del prgreso de la tarea.
     * No es necesario comprobar que no recibe un null porque cuando es llamada ya se ha comprobado que los atributos de la tarea son correctos
     * 
     * @param progreso: int que se refiere al progreso de la tarea
     */
    public void setProgreso(int progreso) {
        porcentajeSpinner.setValue(progreso);
    }

    /**
     * Setter del CheckBox de la completitud de la tarea.
     * No es necesario comprobar que no recibe un null porque cuando es llamada ya se ha comprobado que los atributos de la tarea son correctos
     * 
     * @param completado: boolean que se refiere a la completitud de la tarea
     */
    public void setCompletado(boolean completado) {
        completadoCheckBox.setSelected(completado);
    }

    /**
     * Setter de la etiqueta del texto de error
     * 
     * @param s: String que se refiere al mensaje de error
     */
    public void setError(String s){
        erroresLabel.setText(s);
    }
    
    /**
     * Setter de la visibilidad del Spinner del progreso
     * 
     * @param visible: boolean que se refiere a la visibilidad del spinner
     */
    public void setSpinnerVisible(boolean visible) {
        porcentajeSpinner.setEnabled(visible);
    }

    /**
     * Funcion que limpia y reinicia todos los campos.
     * Los campos de texto los deja vacios y el resto de elementos los pone a su valor por defecto
     */
    public void limpiarCampos(){
        anadirNombreTareaTextField.setText("");
        descripcionTextArea.setText("");
        fechaDateChooser.setDate(java.sql.Date.valueOf(java.time.LocalDate.now()));
        prioridadComboBox.setSelectedIndex(0);
        porcentajeSpinner.setValue(0);
        completadoCheckBox.setSelected(false);
        listaTareasList.clearSelection();
        verNombreTareaLabel.setText("");
        verDescripcionTextArea.setText("");
        verFechaModificableLabel.setText("");
        verPrioridadModificableLabel.setText("");
        verProgresoProgressBar.setValue(0);
        verProgresoNumeroNoModificableLabel.setText("");
        porcentajeSpinner.setEnabled(true);
        erroresLabel.setText("");
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton GestorListasButton;
    private javax.swing.JButton MenuButton;
    private javax.swing.JLabel anadirNombreTareaLabel;
    private javax.swing.JTextField anadirNombreTareaTextField;
    private javax.swing.JLabel anadirProgresoLabel;
    private javax.swing.JCheckBox completadoCheckBox;
    private javax.swing.JLabel descripcionLabel;
    private javax.swing.JScrollPane descripcionScrollPane;
    private javax.swing.JTextArea descripcionTextArea;
    private javax.swing.JButton editarButton;
    private javax.swing.JButton eliminarButton;
    private javax.swing.JLabel erroresLabel;
    private com.toedter.calendar.JDateChooser fechaDateChooser;
    private javax.swing.JLabel fechaLabel;
    private javax.swing.JButton guardarButton;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel10;
    private javax.swing.JPanel jPanel11;
    private javax.swing.JPanel jPanel12;
    private javax.swing.JPanel jPanel13;
    private javax.swing.JPanel jPanel14;
    private javax.swing.JPanel jPanel16;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel26;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel31;
    private javax.swing.JPanel jPanel32;
    private javax.swing.JPanel jPanel35;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel9;
    private javax.swing.JButton limpiarButton;
    private javax.swing.JLabel listaActualLabel;
    private javax.swing.JList<String> listaTareasList;
    private javax.swing.JScrollPane listaTareasScrollPane;
    private javax.swing.JSpinner porcentajeSpinner;
    private javax.swing.JComboBox<String> prioridadComboBox;
    private javax.swing.JLabel prioridadLabel;
    private javax.swing.JComboBox<String> seleccionarListaComboBox;
    private javax.swing.JScrollPane verDescripcionJSCroll;
    private javax.swing.JLabel verDescripcionNoModificableLabel;
    private javax.swing.JTextArea verDescripcionTextArea;
    private javax.swing.JLabel verFechaModificableLabel;
    private javax.swing.JLabel verFechaNoModificableLabel;
    private javax.swing.JLabel verListaModificableLabel;
    private javax.swing.JLabel verListaNoModificableLabel;
    private javax.swing.JLabel verNombreTareaLabel;
    private javax.swing.JLabel verNombreTareaNoModificableLabel;
    private javax.swing.JLabel verPrioridadModificableLabel;
    private javax.swing.JLabel verPrioridadNoModificableLabel;
    private javax.swing.JLabel verProgresoLabel;
    private javax.swing.JLabel verProgresoNumeroNoModificableLabel;
    private javax.swing.JProgressBar verProgresoProgressBar;
    // End of variables declaration//GEN-END:variables
}
