/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package uva.ipc.practica2.vista;

import java.util.ArrayList;
import uva.ipc.practica2.modelo.ListaTareas;


/**
 *
 * @author tomip
 */
public class VistaGestorListas extends javax.swing.JFrame {
    
    private ControladorGestorListas controlador;

    /**
     * Creates new form VistaGestorListas
     */
    public VistaGestorListas() {
        initComponents();
        this.controlador = new ControladorGestorListas(this);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        jPanel5 = new javax.swing.JPanel();
        listasLabel = new javax.swing.JLabel();
        listaListasScrollPane = new javax.swing.JScrollPane();
        listaListasList = new javax.swing.JList<>();
        jPanel6 = new javax.swing.JPanel();
        jPanel15 = new javax.swing.JPanel();
        anadirListaLabel = new javax.swing.JLabel();
        anadirListaTextField = new javax.swing.JTextField();
        jPanel16 = new javax.swing.JPanel();
        anadirListaButton = new javax.swing.JButton();
        jPanel17 = new javax.swing.JPanel();
        jPanel4 = new javax.swing.JPanel();
        jPanel7 = new javax.swing.JPanel();
        verNombreListaLabel = new javax.swing.JLabel();
        verNombreListaTextField = new javax.swing.JTextField();
        jPanel8 = new javax.swing.JPanel();
        tareasCompletadasLabel = new javax.swing.JLabel();
        jPanel9 = new javax.swing.JPanel();
        tareasCompletadasScrollPane = new javax.swing.JScrollPane();
        jList3 = new javax.swing.JList<>();
        jPanel10 = new javax.swing.JPanel();
        tareasPendientesLabel = new javax.swing.JLabel();
        jPanel11 = new javax.swing.JPanel();
        tareasPendientesScrollPane = new javax.swing.JScrollPane();
        jList4 = new javax.swing.JList<>();
        jPanel12 = new javax.swing.JPanel();
        verNumTareasCompletadasLabel = new javax.swing.JLabel();
        verNumTareasCompletadasTextField = new javax.swing.JTextField();
        jPanel13 = new javax.swing.JPanel();
        completarTareaButton = new javax.swing.JButton();
        jPanel14 = new javax.swing.JPanel();
        errorLabel = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        irMenuButton = new javax.swing.JButton();
        irTareasButton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new java.awt.GridLayout(2, 1));

        jPanel2.setLayout(new java.awt.GridLayout(1, 2));

        jPanel3.setLayout(new java.awt.GridLayout(2, 1));

        jPanel5.setLayout(new java.awt.BorderLayout());

        listasLabel.setText("Listas creadas:");
        jPanel5.add(listasLabel, java.awt.BorderLayout.PAGE_START);

        listaListasList.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        listaListasScrollPane.setViewportView(listaListasList);

        jPanel5.add(listaListasScrollPane, java.awt.BorderLayout.CENTER);

        jPanel3.add(jPanel5);

        jPanel6.setLayout(new java.awt.GridLayout(2, 1));

        jPanel15.setLayout(new java.awt.BorderLayout());

        anadirListaLabel.setText("Nombre de la nueva lista: ");
        jPanel15.add(anadirListaLabel, java.awt.BorderLayout.CENTER);
        jPanel15.add(anadirListaTextField, java.awt.BorderLayout.PAGE_END);

        jPanel6.add(jPanel15);

        jPanel16.setLayout(new java.awt.GridBagLayout());

        anadirListaButton.setText("Añadir Lista");
        anadirListaButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                anadirListaButtonActionPerformed(evt);
            }
        });
        jPanel16.add(anadirListaButton, new java.awt.GridBagConstraints());
        jPanel16.add(jPanel17, new java.awt.GridBagConstraints());

        jPanel6.add(jPanel16);

        jPanel3.add(jPanel6);

        jPanel2.add(jPanel3);

        jPanel4.setLayout(new java.awt.GridLayout(8, 1));

        jPanel7.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.LEFT));

        verNombreListaLabel.setText("Lista:");
        jPanel7.add(verNombreListaLabel);

        verNombreListaTextField.setText("jTextField1");
        verNombreListaTextField.setEnabled(false);
        verNombreListaTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                verNombreListaTextFieldActionPerformed(evt);
            }
        });
        jPanel7.add(verNombreListaTextField);

        jPanel4.add(jPanel7);

        jPanel8.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.LEFT));

        tareasCompletadasLabel.setText("Tareas completadas:");
        jPanel8.add(tareasCompletadasLabel);

        jPanel4.add(jPanel8);

        jPanel9.setLayout(new java.awt.BorderLayout());

        jList3.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        tareasCompletadasScrollPane.setViewportView(jList3);

        jPanel9.add(tareasCompletadasScrollPane, java.awt.BorderLayout.CENTER);

        jPanel4.add(jPanel9);

        jPanel10.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.LEFT));

        tareasPendientesLabel.setText("Tareas pendientes");
        jPanel10.add(tareasPendientesLabel);

        jPanel4.add(jPanel10);

        jPanel11.setLayout(new java.awt.BorderLayout());

        jList4.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        tareasPendientesScrollPane.setViewportView(jList4);

        jPanel11.add(tareasPendientesScrollPane, java.awt.BorderLayout.CENTER);

        jPanel4.add(jPanel11);

        verNumTareasCompletadasLabel.setText("Tareas Completadas");
        jPanel12.add(verNumTareasCompletadasLabel);

        verNumTareasCompletadasTextField.setText("33");
        verNumTareasCompletadasTextField.setEnabled(false);
        verNumTareasCompletadasTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                verNumTareasCompletadasTextFieldActionPerformed(evt);
            }
        });
        jPanel12.add(verNumTareasCompletadasTextField);

        jPanel4.add(jPanel12);

        completarTareaButton.setText("Completar Tarea");
        jPanel13.add(completarTareaButton);

        jPanel4.add(jPanel13);

        errorLabel.setForeground(new java.awt.Color(255, 0, 0));
        errorLabel.setText("Error");
        jPanel14.add(errorLabel);

        jPanel4.add(jPanel14);

        jPanel2.add(jPanel4);

        getContentPane().add(jPanel2);

        jPanel1.setMaximumSize(new java.awt.Dimension(116, 33));
        jPanel1.setMinimumSize(new java.awt.Dimension(116, 33));
        jPanel1.setPreferredSize(new java.awt.Dimension(116, 33));

        irMenuButton.setText("Volver al menú principal");
        irMenuButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                irMenuButtonActionPerformed(evt);
            }
        });
        jPanel1.add(irMenuButton);

        irTareasButton.setText("Ir al Gestor de Tareas");
        irTareasButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                irTareasButtonActionPerformed(evt);
            }
        });
        jPanel1.add(irTareasButton);

        getContentPane().add(jPanel1);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void verNombreListaTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_verNombreListaTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_verNombreListaTextFieldActionPerformed

    private void irTareasButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_irTareasButtonActionPerformed
        // TODO add your handling code here:
        controlador.procesarEventoVistaTareas();
    }//GEN-LAST:event_irTareasButtonActionPerformed

    private void irMenuButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_irMenuButtonActionPerformed
        // TODO add your handling code here:
        controlador.procesarEventoVistaMenu();
    }//GEN-LAST:event_irMenuButtonActionPerformed

    private void verNumTareasCompletadasTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_verNumTareasCompletadasTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_verNumTareasCompletadasTextFieldActionPerformed

    private void anadirListaButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_anadirListaButtonActionPerformed
        // TODO add your handling code here:
        controlador.procesarEventoGuardar();
    }//GEN-LAST:event_anadirListaButtonActionPerformed
    
    public void actualizarListas(ArrayList<ListaTareas> listas) {
        String[] listasArray = new String[listas.size()];
    
        for (int i = 0; i < listas.size(); i++) {
            listasArray[i] = listas.get(i).getNombre();
        }
        listaListasList.setListData(listasArray);
    }
    
    public String getNombreNuevaLista(){
        return anadirListaTextField.getText();
    }
   

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton anadirListaButton;
    private javax.swing.JLabel anadirListaLabel;
    private javax.swing.JTextField anadirListaTextField;
    private javax.swing.JButton completarTareaButton;
    private javax.swing.JLabel errorLabel;
    private javax.swing.JButton irMenuButton;
    private javax.swing.JButton irTareasButton;
    private javax.swing.JList<String> jList3;
    private javax.swing.JList<String> jList4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel10;
    private javax.swing.JPanel jPanel11;
    private javax.swing.JPanel jPanel12;
    private javax.swing.JPanel jPanel13;
    private javax.swing.JPanel jPanel14;
    private javax.swing.JPanel jPanel15;
    private javax.swing.JPanel jPanel16;
    private javax.swing.JPanel jPanel17;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JPanel jPanel9;
    private javax.swing.JList<String> listaListasList;
    private javax.swing.JScrollPane listaListasScrollPane;
    private javax.swing.JLabel listasLabel;
    private javax.swing.JLabel tareasCompletadasLabel;
    private javax.swing.JScrollPane tareasCompletadasScrollPane;
    private javax.swing.JLabel tareasPendientesLabel;
    private javax.swing.JScrollPane tareasPendientesScrollPane;
    private javax.swing.JLabel verNombreListaLabel;
    private javax.swing.JTextField verNombreListaTextField;
    private javax.swing.JLabel verNumTareasCompletadasLabel;
    private javax.swing.JTextField verNumTareasCompletadasTextField;
    // End of variables declaration//GEN-END:variables
}
