/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package uva.ipc.practica2.vista;

import java.util.Date;
import uva.ipc.practica2.modelo.ListaTareas;
import uva.ipc.practica2.modelo.Tarea;
import java.text.SimpleDateFormat;
import java.util.ArrayList;
import javax.swing.DefaultComboBoxModel;
import javax.swing.ListSelectionModel;

/**
 * Clase que modifica y controla todo lo relacionado con la vista
 * 
 * @author tomruiz, irereto
 */
public class VistaGestorTareas extends javax.swing.JFrame {

    private ControladorGestorTareas controlador;

     /**
     * Inicializador de la vista
     */
    public VistaGestorTareas() {
        initComponents();
        this.controlador = new ControladorGestorTareas(this);
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        jPanel1 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        jPanel6 = new javax.swing.JPanel();
        jPanel22 = new javax.swing.JPanel();
        anadirNombreTareaLabel = new javax.swing.JLabel();
        jPanel21 = new javax.swing.JPanel();
        anadirNombreTareaTextField = new javax.swing.JTextField();
        jPanel24 = new javax.swing.JPanel();
        jPanel25 = new javax.swing.JPanel();
        jPanel28 = new javax.swing.JPanel();
        jPanel29 = new javax.swing.JPanel();
        jPanel5 = new javax.swing.JPanel();
        jPanel19 = new javax.swing.JPanel();
        descripcionLabel = new javax.swing.JLabel();
        jPanel20 = new javax.swing.JPanel();
        descripcionScrollPane = new javax.swing.JScrollPane();
        descripcionTextArea = new javax.swing.JTextArea();
        jPanel4 = new javax.swing.JPanel();
        jPanel7 = new javax.swing.JPanel();
        jPanel17 = new javax.swing.JPanel();
        fechaLabel = new javax.swing.JLabel();
        fechaDateChooser = new com.toedter.calendar.JDateChooser();
        jPanel18 = new javax.swing.JPanel();
        prioridadLabel = new javax.swing.JLabel();
        prioridadComboBox = new javax.swing.JComboBox<>();
        jPanel8 = new javax.swing.JPanel();
        anadirProgresoLabel = new javax.swing.JLabel();
        porcentajeSpinner = new javax.swing.JSpinner();
        jPanel27 = new javax.swing.JPanel();
        completadoCheckBox = new javax.swing.JCheckBox();
        jPanel30 = new javax.swing.JPanel();
        listaActualLabel = new javax.swing.JLabel();
        seleccionarListaComboBox = new javax.swing.JComboBox<>();
        jPanel23 = new javax.swing.JPanel();
        erroresLabel = new javax.swing.JLabel();
        jPanel9 = new javax.swing.JPanel();
        guardarButton = new javax.swing.JButton();
        limpiarButton = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jPanel10 = new javax.swing.JPanel();
        listaTareasScrollPane = new javax.swing.JScrollPane();
        listaTareasList = new javax.swing.JList<>();
        jPanel11 = new javax.swing.JPanel();
        jPanel12 = new javax.swing.JPanel();
        verNombreTareaLabel = new javax.swing.JLabel();
        verNombreTareaNoModificableLabel = new javax.swing.JLabel();
        jPanel13 = new javax.swing.JPanel();
        verDescripcionJSCroll = new javax.swing.JScrollPane();
        verDescripcionTextArea = new javax.swing.JTextArea();
        verDescripcionNoModificableLabel = new javax.swing.JLabel();
        jPanel14 = new javax.swing.JPanel();
        verFechaNoModificableLabel = new javax.swing.JLabel();
        verFechaModificableLabel = new javax.swing.JLabel();
        jPanel15 = new javax.swing.JPanel();
        verPrioridadNoModificableLabel = new javax.swing.JLabel();
        verPrioridadModificableLabel = new javax.swing.JLabel();
        verProgresoLabel = new javax.swing.JLabel();
        verProgresoNumeroNoModificableLabel = new javax.swing.JLabel();
        verProgresoProgressBar = new javax.swing.JProgressBar();
        jPanel16 = new javax.swing.JPanel();
        editarButton = new javax.swing.JButton();
        eliminarButton = new javax.swing.JButton();
        jPanel26 = new javax.swing.JPanel();
        GestorListasButton = new javax.swing.JButton();
        jPanel32 = new javax.swing.JPanel();
        jPanel31 = new javax.swing.JPanel();
        MenuButton = new javax.swing.JButton();
        jPanel35 = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(255, 255, 204));
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        setMinimumSize(new java.awt.Dimension(1000, 700));
        setPreferredSize(new java.awt.Dimension(1700, 800));
        getContentPane().setLayout(new java.awt.GridBagLayout());

        jPanel1.setBackground(new java.awt.Color(255, 255, 204));
        jPanel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel1.setMinimumSize(new java.awt.Dimension(100, 50));
        jPanel1.setName(""); // NOI18N
        jPanel1.setPreferredSize(new java.awt.Dimension(750, 860));
        jPanel1.setLayout(new java.awt.GridBagLayout());

        jPanel3.setBackground(new java.awt.Color(255, 255, 204));
        jPanel3.setMinimumSize(new java.awt.Dimension(75, 86));
        jPanel3.setName(""); // NOI18N
        jPanel3.setLayout(new java.awt.GridBagLayout());

        jPanel6.setBackground(new java.awt.Color(255, 255, 204));
        jPanel6.setMinimumSize(new java.awt.Dimension(75, 32));
        jPanel6.setName(""); // NOI18N
        jPanel6.setLayout(new java.awt.GridBagLayout());

        jPanel22.setBackground(new java.awt.Color(255, 255, 204));
        jPanel22.setMaximumSize(new java.awt.Dimension(798, 182));
        jPanel22.setMinimumSize(new java.awt.Dimension(37, 26));
        jPanel22.setPreferredSize(new java.awt.Dimension(350, 26));
        jPanel22.setRequestFocusEnabled(false);
        jPanel22.setLayout(new java.awt.GridBagLayout());

        anadirNombreTareaLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        anadirNombreTareaLabel.setText("Nombre de la tarea");
        anadirNombreTareaLabel.setHorizontalTextPosition(javax.swing.SwingConstants.LEFT);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.weighty = 1.0;
        jPanel22.add(anadirNombreTareaLabel, gridBagConstraints);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.weightx = 0.3;
        gridBagConstraints.weighty = 1.0;
        jPanel6.add(jPanel22, gridBagConstraints);

        jPanel21.setBackground(new java.awt.Color(255, 255, 204));
        jPanel21.setMinimumSize(new java.awt.Dimension(37, 32));
        jPanel21.setName(""); // NOI18N
        jPanel21.setLayout(new java.awt.GridBagLayout());

        anadirNombreTareaTextField.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        anadirNombreTareaTextField.setMaximumSize(new java.awt.Dimension(2147483647, 32));
        anadirNombreTareaTextField.setMinimumSize(new java.awt.Dimension(64, 32));
        anadirNombreTareaTextField.setName(""); // NOI18N
        anadirNombreTareaTextField.setNextFocusableComponent(descripcionTextArea);
        anadirNombreTareaTextField.setPreferredSize(new java.awt.Dimension(450, 32));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 3;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.weighty = 0.2;
        jPanel21.add(anadirNombreTareaTextField, gridBagConstraints);

        jPanel24.setBackground(new java.awt.Color(255, 255, 204));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.weighty = 0.2;
        jPanel21.add(jPanel24, gridBagConstraints);

        jPanel25.setBackground(new java.awt.Color(255, 255, 204));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 4;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.weighty = 0.2;
        jPanel21.add(jPanel25, gridBagConstraints);

        jPanel28.setBackground(new java.awt.Color(255, 255, 204));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.weighty = 0.2;
        jPanel21.add(jPanel28, gridBagConstraints);

        jPanel29.setBackground(new java.awt.Color(255, 255, 204));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 5;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.weighty = 0.2;
        jPanel21.add(jPanel29, gridBagConstraints);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.weightx = 0.7;
        gridBagConstraints.weighty = 1.0;
        jPanel6.add(jPanel21, gridBagConstraints);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.weighty = 0.3;
        jPanel3.add(jPanel6, gridBagConstraints);

        jPanel5.setBackground(new java.awt.Color(255, 255, 204));
        jPanel5.setMinimumSize(new java.awt.Dimension(75, 50));
        jPanel5.setName(""); // NOI18N
        jPanel5.setLayout(new java.awt.GridBagLayout());

        jPanel19.setBackground(new java.awt.Color(255, 255, 204));
        jPanel19.setLayout(new java.awt.GridBagLayout());

        descripcionLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        descripcionLabel.setText("Descripción:");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.weighty = 1.0;
        jPanel19.add(descripcionLabel, gridBagConstraints);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.weightx = 0.3;
        gridBagConstraints.weighty = 1.0;
        jPanel5.add(jPanel19, gridBagConstraints);

        jPanel20.setBackground(new java.awt.Color(255, 255, 204));
        jPanel20.setLayout(new java.awt.GridBagLayout());

        descripcionScrollPane.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_NEVER);
        descripcionScrollPane.setVerticalScrollBarPolicy(javax.swing.ScrollPaneConstants.VERTICAL_SCROLLBAR_ALWAYS);
        descripcionScrollPane.setHorizontalScrollBar(null);
        descripcionScrollPane.setPreferredSize(new java.awt.Dimension(144, 86));

        descripcionTextArea.setColumns(20);
        descripcionTextArea.setLineWrap(true);
        descripcionTextArea.setRows(5);
        descripcionTextArea.setToolTipText("");
        descripcionTextArea.setWrapStyleWord(true);
        descripcionTextArea.setName(""); // NOI18N
        descripcionTextArea.setNextFocusableComponent(fechaDateChooser);
        descripcionTextArea.setPreferredSize(new java.awt.Dimension(450, 74));
        descripcionScrollPane.setViewportView(descripcionTextArea);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.weighty = 1.0;
        jPanel20.add(descripcionScrollPane, gridBagConstraints);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.weightx = 0.7;
        gridBagConstraints.weighty = 1.0;
        jPanel5.add(jPanel20, gridBagConstraints);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.weighty = 0.7;
        jPanel3.add(jPanel5, gridBagConstraints);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.weighty = 0.5;
        gridBagConstraints.insets = new java.awt.Insets(10, 10, 10, 10);
        jPanel1.add(jPanel3, gridBagConstraints);

        jPanel4.setBackground(new java.awt.Color(255, 255, 204));
        jPanel4.setMinimumSize(new java.awt.Dimension(75, 86));
        jPanel4.setName(""); // NOI18N
        jPanel4.setLayout(new java.awt.GridBagLayout());

        jPanel7.setBackground(new java.awt.Color(255, 255, 204));
        jPanel7.setMinimumSize(new java.awt.Dimension(75, 86));
        jPanel7.setName(""); // NOI18N
        jPanel7.setLayout(new java.awt.GridBagLayout());

        jPanel17.setBackground(new java.awt.Color(255, 255, 204));
        jPanel17.setMinimumSize(new java.awt.Dimension(37, 32));
        jPanel17.setLayout(new java.awt.GridBagLayout());

        fechaLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        fechaLabel.setText("Fecha: ");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.weightx = 0.5;
        gridBagConstraints.weighty = 1.0;
        jPanel17.add(fechaLabel, gridBagConstraints);

        fechaDateChooser.setBackground(new java.awt.Color(255, 255, 204));
        fechaDateChooser.setDate(java.sql.Date.valueOf(java.time.LocalDate.now()));
        fechaDateChooser.setDateFormatString("dd/MM/yyyy");
        fechaDateChooser.setMaxSelectableDate(new java.util.Date(253370764872000L));
        fechaDateChooser.setMinimumSize(new java.awt.Dimension(120, 28));
        fechaDateChooser.setNextFocusableComponent(prioridadComboBox);
        fechaDateChooser.setPreferredSize(new java.awt.Dimension(120, 28));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.weightx = 0.5;
        gridBagConstraints.weighty = 1.0;
        jPanel17.add(fechaDateChooser, gridBagConstraints);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.weightx = 0.5;
        gridBagConstraints.weighty = 1.0;
        jPanel7.add(jPanel17, gridBagConstraints);

        jPanel18.setBackground(new java.awt.Color(255, 255, 204));
        jPanel18.setMinimumSize(new java.awt.Dimension(37, 32));
        jPanel18.setName(""); // NOI18N
        jPanel18.setPreferredSize(new java.awt.Dimension(450, 32));
        jPanel18.setLayout(new java.awt.GridBagLayout());

        prioridadLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        prioridadLabel.setText("Prioridad");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.weightx = 0.5;
        gridBagConstraints.weighty = 1.0;
        jPanel18.add(prioridadLabel, gridBagConstraints);

        prioridadComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Baja", "Media", "Alta" }));
        prioridadComboBox.setName(""); // NOI18N
        prioridadComboBox.setNextFocusableComponent(porcentajeSpinner);
        prioridadComboBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                prioridadComboBoxActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.weightx = 0.5;
        gridBagConstraints.weighty = 1.0;
        jPanel18.add(prioridadComboBox, gridBagConstraints);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.weightx = 0.5;
        gridBagConstraints.weighty = 1.0;
        jPanel7.add(jPanel18, gridBagConstraints);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.weighty = 0.2;
        gridBagConstraints.insets = new java.awt.Insets(10, 10, 10, 10);
        jPanel4.add(jPanel7, gridBagConstraints);

        jPanel8.setBackground(new java.awt.Color(255, 255, 204));
        jPanel8.setMinimumSize(new java.awt.Dimension(75, 86));
        jPanel8.setName(""); // NOI18N
        jPanel8.setPreferredSize(new java.awt.Dimension(550, 32));
        jPanel8.setLayout(new java.awt.GridBagLayout());

        anadirProgresoLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        anadirProgresoLabel.setText("Progreso:");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.weightx = 0.3;
        gridBagConstraints.weighty = 1.0;
        jPanel8.add(anadirProgresoLabel, gridBagConstraints);

        porcentajeSpinner.setModel(new javax.swing.SpinnerNumberModel(0, 0, 100, 1));
        porcentajeSpinner.setMinimumSize(new java.awt.Dimension(60, 28));
        porcentajeSpinner.setName(""); // NOI18N
        porcentajeSpinner.setNextFocusableComponent(completadoCheckBox);
        porcentajeSpinner.setPreferredSize(new java.awt.Dimension(60, 28));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.weightx = 0.3;
        gridBagConstraints.weighty = 1.0;
        jPanel8.add(porcentajeSpinner, gridBagConstraints);

        jPanel27.setBackground(new java.awt.Color(255, 255, 204));

        javax.swing.GroupLayout jPanel27Layout = new javax.swing.GroupLayout(jPanel27);
        jPanel27.setLayout(jPanel27Layout);
        jPanel27Layout.setHorizontalGroup(
            jPanel27Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        jPanel27Layout.setVerticalGroup(
            jPanel27Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 3;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.weightx = 0.1;
        gridBagConstraints.weighty = 1.0;
        jPanel8.add(jPanel27, gridBagConstraints);

        completadoCheckBox.setBackground(new java.awt.Color(255, 255, 204));
        completadoCheckBox.setText("Completado");
        completadoCheckBox.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        completadoCheckBox.setNextFocusableComponent(guardarButton);
        completadoCheckBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                completadoCheckBoxActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 4;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.weightx = 0.3;
        gridBagConstraints.weighty = 1.0;
        jPanel8.add(completadoCheckBox, gridBagConstraints);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.weighty = 0.2;
        gridBagConstraints.insets = new java.awt.Insets(10, 10, 10, 10);
        jPanel4.add(jPanel8, gridBagConstraints);

        jPanel30.setBackground(new java.awt.Color(255, 255, 204));
        jPanel30.setMinimumSize(new java.awt.Dimension(75, 86));
        jPanel30.setName(""); // NOI18N
        jPanel30.setPreferredSize(new java.awt.Dimension(550, 32));
        jPanel30.setLayout(new java.awt.GridBagLayout());

        listaActualLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        listaActualLabel.setText("Lista actual:");
        listaActualLabel.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.weightx = 0.5;
        gridBagConstraints.weighty = 1.0;
        jPanel30.add(listaActualLabel, gridBagConstraints);

        seleccionarListaComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        seleccionarListaComboBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                seleccionarListaComboBoxActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.weightx = 0.5;
        gridBagConstraints.weighty = 1.0;
        jPanel30.add(seleccionarListaComboBox, gridBagConstraints);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 3;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.weighty = 0.2;
        gridBagConstraints.insets = new java.awt.Insets(10, 10, 10, 10);
        jPanel4.add(jPanel30, gridBagConstraints);

        jPanel23.setBackground(new java.awt.Color(255, 255, 204));
        jPanel23.setLayout(new java.awt.GridBagLayout());

        erroresLabel.setBackground(new java.awt.Color(255, 255, 204));
        erroresLabel.setFont(new java.awt.Font("Liberation Sans", 1, 15)); // NOI18N
        erroresLabel.setForeground(new java.awt.Color(153, 0, 51));
        erroresLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        erroresLabel.setAlignmentX(0.5F);
        erroresLabel.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.weighty = 1.0;
        jPanel23.add(erroresLabel, gridBagConstraints);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 4;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.weighty = 0.2;
        gridBagConstraints.insets = new java.awt.Insets(10, 10, 10, 10);
        jPanel4.add(jPanel23, gridBagConstraints);

        jPanel9.setBackground(new java.awt.Color(255, 255, 204));
        jPanel9.setMinimumSize(new java.awt.Dimension(75, 86));
        jPanel9.setName(""); // NOI18N
        jPanel9.setPreferredSize(new java.awt.Dimension(550, 33));
        jPanel9.setLayout(new java.awt.GridBagLayout());

        guardarButton.setBackground(new java.awt.Color(255, 153, 0));
        guardarButton.setText("Guardar");
        guardarButton.setMaximumSize(null);
        guardarButton.setMinimumSize(new java.awt.Dimension(82, 28));
        guardarButton.setPreferredSize(new java.awt.Dimension(87, 35));
        guardarButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                guardarButtonActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.weightx = 0.3;
        gridBagConstraints.weighty = 1.0;
        gridBagConstraints.insets = new java.awt.Insets(0, 0, 0, 10);
        jPanel9.add(guardarButton, gridBagConstraints);

        limpiarButton.setBackground(new java.awt.Color(255, 153, 0));
        limpiarButton.setText("Limpiar");
        limpiarButton.setPreferredSize(new java.awt.Dimension(82, 35));
        limpiarButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                limpiarButtonActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.weightx = 0.3;
        gridBagConstraints.weighty = 1.0;
        gridBagConstraints.insets = new java.awt.Insets(0, 10, 0, 0);
        jPanel9.add(limpiarButton, gridBagConstraints);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 5;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.weighty = 0.2;
        gridBagConstraints.insets = new java.awt.Insets(10, 10, 10, 10);
        jPanel4.add(jPanel9, gridBagConstraints);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.weighty = 0.5;
        gridBagConstraints.insets = new java.awt.Insets(10, 10, 10, 10);
        jPanel1.add(jPanel4, gridBagConstraints);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.weightx = 0.5;
        gridBagConstraints.weighty = 0.95;
        gridBagConstraints.insets = new java.awt.Insets(10, 10, 10, 10);
        getContentPane().add(jPanel1, gridBagConstraints);

        jPanel2.setBackground(new java.awt.Color(255, 255, 204));
        jPanel2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel2.setMinimumSize(new java.awt.Dimension(75, 86));
        jPanel2.setPreferredSize(new java.awt.Dimension(750, 860));
        jPanel2.setLayout(new java.awt.GridBagLayout());

        jPanel10.setBackground(new java.awt.Color(255, 255, 204));
        jPanel10.setLayout(new java.awt.GridBagLayout());

        listaTareasScrollPane.setBackground(new java.awt.Color(255, 255, 204));

        listaTareasList.setSelectionMode(ListSelectionModel.SINGLE_SELECTION);
        listaTareasList.addListSelectionListener(new javax.swing.event.ListSelectionListener() {
            public void valueChanged(javax.swing.event.ListSelectionEvent evt) {
                listaTareasListValueChanged(evt);
            }
        });
        listaTareasScrollPane.setViewportView(listaTareasList);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.weighty = 1.0;
        jPanel10.add(listaTareasScrollPane, gridBagConstraints);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.weighty = 0.5;
        gridBagConstraints.insets = new java.awt.Insets(10, 10, 10, 10);
        jPanel2.add(jPanel10, gridBagConstraints);

        jPanel11.setBackground(new java.awt.Color(255, 255, 204));
        jPanel11.setBorder(javax.swing.BorderFactory.createTitledBorder(""));
        jPanel11.setMinimumSize(new java.awt.Dimension(75, 86));
        jPanel11.setLayout(new java.awt.GridBagLayout());

        jPanel12.setBackground(new java.awt.Color(255, 255, 204));
        jPanel12.setLayout(new java.awt.GridBagLayout());

        verNombreTareaLabel.setBackground(new java.awt.Color(255, 255, 255));
        verNombreTareaLabel.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.weightx = 0.9;
        gridBagConstraints.weighty = 1.0;
        jPanel12.add(verNombreTareaLabel, gridBagConstraints);

        verNombreTareaNoModificableLabel.setBackground(new java.awt.Color(255, 255, 255));
        verNombreTareaNoModificableLabel.setText("Nombre:");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.weightx = 0.1;
        gridBagConstraints.weighty = 1.0;
        jPanel12.add(verNombreTareaNoModificableLabel, gridBagConstraints);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.weighty = 0.2;
        gridBagConstraints.insets = new java.awt.Insets(10, 10, 10, 10);
        jPanel11.add(jPanel12, gridBagConstraints);

        jPanel13.setBackground(new java.awt.Color(255, 255, 204));
        jPanel13.setLayout(new java.awt.GridBagLayout());

        verDescripcionJSCroll.setBackground(new java.awt.Color(255, 153, 255));
        verDescripcionJSCroll.setEnabled(false);

        verDescripcionTextArea.setEditable(false);
        verDescripcionTextArea.setBackground(new java.awt.Color(255, 153, 255));
        verDescripcionTextArea.setColumns(20);
        verDescripcionTextArea.setRows(5);
        verDescripcionTextArea.setAutoscrolls(false);
        verDescripcionTextArea.setOpaque(false);
        verDescripcionJSCroll.setViewportView(verDescripcionTextArea);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.weighty = 0.9;
        jPanel13.add(verDescripcionJSCroll, gridBagConstraints);

        verDescripcionNoModificableLabel.setBackground(new java.awt.Color(255, 153, 255));
        verDescripcionNoModificableLabel.setText("Descripción:");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.weighty = 0.1;
        jPanel13.add(verDescripcionNoModificableLabel, gridBagConstraints);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.weighty = 0.2;
        gridBagConstraints.insets = new java.awt.Insets(10, 10, 10, 10);
        jPanel11.add(jPanel13, gridBagConstraints);

        jPanel14.setBackground(new java.awt.Color(255, 255, 204));
        jPanel14.setLayout(new java.awt.GridBagLayout());

        verFechaNoModificableLabel.setText("Fecha:");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.weightx = 0.1;
        gridBagConstraints.weighty = 1.0;
        jPanel14.add(verFechaNoModificableLabel, gridBagConstraints);

        verFechaModificableLabel.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.weightx = 0.9;
        gridBagConstraints.weighty = 1.0;
        jPanel14.add(verFechaModificableLabel, gridBagConstraints);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 3;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.weighty = 0.2;
        gridBagConstraints.insets = new java.awt.Insets(10, 10, 10, 10);
        jPanel11.add(jPanel14, gridBagConstraints);

        jPanel15.setBackground(new java.awt.Color(255, 255, 204));
        jPanel15.setMinimumSize(new java.awt.Dimension(50, 26));
        jPanel15.setLayout(new java.awt.GridBagLayout());

        verPrioridadNoModificableLabel.setText("Prioridad:");
        jPanel15.add(verPrioridadNoModificableLabel, new java.awt.GridBagConstraints());
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.weightx = 0.2;
        gridBagConstraints.weighty = 1.0;
        jPanel15.add(verPrioridadModificableLabel, gridBagConstraints);

        verProgresoLabel.setBackground(new java.awt.Color(255, 255, 255));
        verProgresoLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        verProgresoLabel.setText("Progreso:");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 3;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.weightx = 0.2;
        gridBagConstraints.weighty = 1.0;
        jPanel15.add(verProgresoLabel, gridBagConstraints);
        jPanel15.add(verProgresoNumeroNoModificableLabel, new java.awt.GridBagConstraints());

        verProgresoProgressBar.setBackground(new java.awt.Color(255, 255, 255));
        verProgresoProgressBar.setForeground(new java.awt.Color(0, 204, 51));
        verProgresoProgressBar.setMaximumSize(new java.awt.Dimension(32767, 20));
        verProgresoProgressBar.setMinimumSize(new java.awt.Dimension(10, 20));
        verProgresoProgressBar.setPreferredSize(new java.awt.Dimension(146, 20));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 4;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.weightx = 0.4;
        gridBagConstraints.weighty = 1.0;
        jPanel15.add(verProgresoProgressBar, gridBagConstraints);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 4;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.weighty = 0.2;
        gridBagConstraints.insets = new java.awt.Insets(10, 10, 10, 10);
        jPanel11.add(jPanel15, gridBagConstraints);

        jPanel16.setBackground(new java.awt.Color(255, 255, 204));
        jPanel16.setMinimumSize(new java.awt.Dimension(50, 33));
        jPanel16.setLayout(new java.awt.GridBagLayout());

        editarButton.setBackground(new java.awt.Color(255, 153, 0));
        editarButton.setText("Editar");
        editarButton.setMinimumSize(new java.awt.Dimension(82, 28));
        editarButton.setPreferredSize(new java.awt.Dimension(82, 35));
        editarButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                editarButtonActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.weightx = 0.5;
        gridBagConstraints.weighty = 1.0;
        gridBagConstraints.insets = new java.awt.Insets(0, 0, 0, 10);
        jPanel16.add(editarButton, gridBagConstraints);

        eliminarButton.setBackground(new java.awt.Color(255, 153, 0));
        eliminarButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/uva/ipc/practica2/vista/eliminar.png"))); // NOI18N
        eliminarButton.setText("Eliminar");
        eliminarButton.setMinimumSize(new java.awt.Dimension(82, 28));
        eliminarButton.setPreferredSize(new java.awt.Dimension(82, 35));
        eliminarButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                eliminarButtonActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.weightx = 0.5;
        gridBagConstraints.weighty = 1.0;
        gridBagConstraints.insets = new java.awt.Insets(0, 10, 0, 0);
        jPanel16.add(eliminarButton, gridBagConstraints);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 5;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.weighty = 0.2;
        gridBagConstraints.insets = new java.awt.Insets(10, 10, 10, 10);
        jPanel11.add(jPanel16, gridBagConstraints);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.weighty = 0.5;
        gridBagConstraints.insets = new java.awt.Insets(10, 10, 10, 10);
        jPanel2.add(jPanel11, gridBagConstraints);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.weightx = 0.5;
        gridBagConstraints.weighty = 0.95;
        gridBagConstraints.insets = new java.awt.Insets(10, 10, 10, 10);
        getContentPane().add(jPanel2, gridBagConstraints);

        jPanel26.setLayout(new java.awt.GridBagLayout());

        GestorListasButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/uva/ipc/practica2/vista/editar_listas.png"))); // NOI18N
        GestorListasButton.setText("Gestionar Listas");
        GestorListasButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                GestorListasButtonActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 4;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.weightx = 0.25;
        gridBagConstraints.weighty = 1.0;
        gridBagConstraints.insets = new java.awt.Insets(10, 10, 10, 10);
        jPanel26.add(GestorListasButton, gridBagConstraints);

        javax.swing.GroupLayout jPanel32Layout = new javax.swing.GroupLayout(jPanel32);
        jPanel32.setLayout(jPanel32Layout);
        jPanel32Layout.setHorizontalGroup(
            jPanel32Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        jPanel32Layout.setVerticalGroup(
            jPanel32Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.weightx = 0.75;
        gridBagConstraints.weighty = 1.0;
        jPanel26.add(jPanel32, gridBagConstraints);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.weightx = 0.5;
        gridBagConstraints.weighty = 0.05;
        gridBagConstraints.insets = new java.awt.Insets(10, 10, 10, 10);
        getContentPane().add(jPanel26, gridBagConstraints);

        jPanel31.setLayout(new java.awt.GridBagLayout());

        MenuButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/uva/ipc/practica2/vista/flecha_atras.png"))); // NOI18N
        MenuButton.setText("Menú Principal");
        MenuButton.setMaximumSize(new java.awt.Dimension(150, 41));
        MenuButton.setMinimumSize(new java.awt.Dimension(150, 41));
        MenuButton.setPreferredSize(new java.awt.Dimension(150, 41));
        MenuButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MenuButtonActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.weightx = 0.25;
        gridBagConstraints.weighty = 1.0;
        gridBagConstraints.insets = new java.awt.Insets(10, 10, 10, 10);
        jPanel31.add(MenuButton, gridBagConstraints);

        javax.swing.GroupLayout jPanel35Layout = new javax.swing.GroupLayout(jPanel35);
        jPanel35.setLayout(jPanel35Layout);
        jPanel35Layout.setHorizontalGroup(
            jPanel35Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        jPanel35Layout.setVerticalGroup(
            jPanel35Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.weightx = 0.75;
        gridBagConstraints.weighty = 1.0;
        jPanel31.add(jPanel35, gridBagConstraints);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.weightx = 0.5;
        gridBagConstraints.weighty = 0.05;
        gridBagConstraints.insets = new java.awt.Insets(10, 10, 10, 10);
        getContentPane().add(jPanel31, gridBagConstraints);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * Funcion que maneja el evento de seleccionar el boton de guardar.
     * Llama al controlador para que procese el evento
     * 
     * @param evt: evento de accion generado por el click del boton
     */
    private void guardarButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_guardarButtonActionPerformed
        // TODO add your handling code here:
        controlador.procesarEventoGuardar();
    }//GEN-LAST:event_guardarButtonActionPerformed

    
    /**
     * Funcion que maneja el evento de seleccionar el boton de editar.
     * Llama al controlador para que procese el evento
     * 
     * @param evt: evento de accion generado por el click del boton
     */
    private void editarButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_editarButtonActionPerformed
        // TODO add your handling code here:
        controlador.procesarEventoEditar();
    }//GEN-LAST:event_editarButtonActionPerformed

    /**
     * Funcion que maneja el evento de seleccionar una tarea de la lista.
     * Llama al controlador para que procese el evento
     * 
     * @param evt: evento de cambio de seleccion generado por la lista
     */
    private void listaTareasListValueChanged(javax.swing.event.ListSelectionEvent evt) {//GEN-FIRST:event_listaTareasListValueChanged
        // TODO add your handling code here:
        controlador.procesarEventoSeleccionarTarea(listaTareasList.getSelectedValue());
        erroresLabel.setText("");
    }//GEN-LAST:event_listaTareasListValueChanged

    /**
     * Funcion que maneja el evento de seleccionar el boton de eliminar.
     * Llama al controlador para que procese el evento
     * 
     * @param evt: evento de accion generado por el click del boton
     */
    private void eliminarButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_eliminarButtonActionPerformed
        // TODO add your handling code here:
        controlador.procesarEventoEliminar();
    }//GEN-LAST:event_eliminarButtonActionPerformed

    /**
     * Funcion que maneja el evento de seleccionar el boton de limpiar.
     * Llama al controlador para que procese el evento
     * 
     * @param evt: evento de accion generado por el click del boton
     */
    private void limpiarButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_limpiarButtonActionPerformed
        // TODO add your handling code here:
        controlador.procesarEventoLimpiar();
    }//GEN-LAST:event_limpiarButtonActionPerformed

    /**
     * Funcion que maneja el evento de marcar o desmarcar el checkbox.
     * Llama al controlador para que procese el evento
     * 
     * @param evt: evento de accion generado por la interaccion con el checkbox
     */
    private void completadoCheckBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_completadoCheckBoxActionPerformed
        // TODO add your handling code here:
        controlador.procesarEventoCompletado();
        
    }//GEN-LAST:event_completadoCheckBoxActionPerformed

    private void prioridadComboBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_prioridadComboBoxActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_prioridadComboBoxActionPerformed

    private void seleccionarListaComboBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_seleccionarListaComboBoxActionPerformed
        // TODO add your handling code here:
        controlador.procesarCambiarListaSeleccionada();
    }//GEN-LAST:event_seleccionarListaComboBoxActionPerformed

    private void GestorListasButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_GestorListasButtonActionPerformed
        // TODO add your handling code here:
        controlador.procesarEventoVistaListas();
    }//GEN-LAST:event_GestorListasButtonActionPerformed

    private void MenuButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MenuButtonActionPerformed
        // TODO add your handling code here:
        controlador.procesarEventoVistaMenu();
    }//GEN-LAST:event_MenuButtonActionPerformed

    /**
     * Funcion que actualiza la lista de tareas que se muestran.
     * Convierte el ArrayList de tareas un array de String
     * 
     * @param tareas: ArrayList de tareas que tiene que mostrar la lista
     */
    public void actualizarTareas(ArrayList<Tarea> tareas) {
         String[] tareasArray = new String[tareas.size()];
    
        for (int i = 0; i < tareas.size(); i++) {
            tareasArray[i] = tareas.get(i).toString();
        }
        listaTareasList.setListData(tareasArray);
    }
    /**
     * Funcion que actualiza la lista de listas en el desplegable seleccionarLista que se muestran.
     * Convierte el ArrayList de listas en un array de String
     * 
     * @param listas: ArrayList de listas que tiene que mostrar la lista
     */
    public void actualizarListas(ArrayList<ListaTareas> listas) {
        String[] listasArray = new String[listas.size()];
    
        for (int i = 0; i < listas.size(); i++) {
            listasArray[i] = listas.get(i).getNombre();
        }
        seleccionarListaComboBox.setModel(new DefaultComboBoxModel <> (listasArray));
    }
    

    /**
     * Funcion que cambia el texto de los campos no modificables con la informacion
     * de una tarea
     * 
     * @param t: tarea de la cual se quiere mostrar la informacion
     */
    public void cambiarCamposNoModificables(Tarea t){
        SimpleDateFormat formato = new SimpleDateFormat("dd/MM/yyyy");
        verNombreTareaLabel.setText(t.getNombreTarea());
        verDescripcionTextArea.setText(t.getDescripcionTareas());
        verFechaModificableLabel.setText(formato.format(t.getFecha()));
        verPrioridadModificableLabel.setText(t.getPrioridad());
        verProgresoProgressBar.setValue(t.getProgreso());
        verProgresoNumeroNoModificableLabel.setText(Integer.toString(t.getProgreso()));
    }
    
   
    /**
     * Funcion que devuelve el nombre de la tarea ingresada por el usuario
     * 
     * @return el nombre de la tarea
     */
    public String getNombreTarea() {
        return anadirNombreTareaTextField.getText();
    }

    
    /**
     * Funcion que devuelve la descripcion de la tarea ingresada por el usuario
     * 
     * @return la descripcion de la tarea
     */
    public String getDescripcion() {
        return descripcionTextArea.getText();
    }

    /**
     * Funcion que devuelve la fecja de la tarea ingresada por el usuario
     * 
     * @return la fecha de la tarea
     */
    public Date getFecha() {
        Date fecha = (Date) fechaDateChooser.getDate();
        return fecha;
    }

    /**
     * Funcion que devuelve la prioridad de la tarea ingresada por el usuario
     * 
     * @return la prioridad de la tarea
     */
    public String getPrioridad() {
        return (String) prioridadComboBox.getSelectedItem();
    }

    /**
     * Funcion que devuelve el progreso de la tarea ingresada por el usuario
     * 
     * @return el progreso de la tarea
     */
    public int getProgreso() {
        return (int) porcentajeSpinner.getValue();
    }

    /**
     * Funcion que devuelve si la tarea ingresada por el usuario esta completada
     * 
     * @return si la tarea esta completada o no en un boolean
     */
    public boolean getCompletado() {
        return completadoCheckBox.isSelected();
    }
    
    /**
     * Funcion que devuelve la tarea seleccionada de la lista
     * 
     * @return la tarea seleccionada
     */
    public String getTareaSeleccionada(){
        return listaTareasList.getSelectedValue();
    }
    
    
    public int getListaSeleccionada(){
        return seleccionarListaComboBox.getSelectedIndex();
    }
    
    
    
    
    
    /**
     * Setter del campo de texto del nombre de la tarea.
     * No es necesario comprobar que no recibe un null porque cuando es llamada ya se ha comprobado que los atributos de la tarea son correctos
     * 
     * @param nombreTarea: String que se refiere al nombre de la tarea
     */
    public void setNombreTarea(String nombreTarea) {
        anadirNombreTareaTextField.setText(nombreTarea);
    }

    /**
     * Setter del area de texto de la descripcion de la tarea.
     * No es necesario comprobar que no recibe un null porque cuando es llamada ya se ha comprobado que los atributos de la tarea son correctos
     * 
     * @param descripcion: String que se refiere a la descripcion de la tarea
     */
    public void setDescripcion(String descripcion) {
        descripcionTextArea.setText(descripcion);
    }

    /**
     * Setter del dateChooser de la fecha de la tarea.
     * No es necesario comprobar que no recibe un null porque cuando es llamada ya se ha comprobado que los atributos de la tarea son correctos
     * 
     * @param fecha: Date que se refiere a la fecha de la tarea
     */
    public void setFecha(Date fecha) {
        fechaDateChooser.setDate(fecha);
    }

    /**
     * Setter del ComboBox de la prioridad de la tarea.
     * No es necesario comprobar que no recibe un null porque cuando es llamada ya se ha comprobado que los atributos de la tarea son correctos
     * 
     * @param prioridad: String que se refiere a la prioridad de la tarea
     */
    public void setPrioridad(String prioridad) {
        prioridadComboBox.setSelectedItem(prioridad);
    }

    /**
     * Setter del Spinner del prgreso de la tarea.
     * No es necesario comprobar que no recibe un null porque cuando es llamada ya se ha comprobado que los atributos de la tarea son correctos
     * 
     * @param progreso: int que se refiere al progreso de la tarea
     */
    public void setProgreso(int progreso) {
        porcentajeSpinner.setValue(progreso);
    }

    /**
     * Setter del CheckBox de la completitud de la tarea.
     * No es necesario comprobar que no recibe un null porque cuando es llamada ya se ha comprobado que los atributos de la tarea son correctos
     * 
     * @param completado: boolean que se refiere a la completitud de la tarea
     */
    public void setCompletado(boolean completado) {
        completadoCheckBox.setSelected(completado);
    }

    /**
     * Setter de la etiqueta del texto de error
     * 
     * @param s: String que se refiere al mensaje de error
     */
    public void setError(String s){
        erroresLabel.setText(s);
    }
    
    /**
     * Setter de la visibilidad del Spinner del progreso
     * 
     * @param visible: boolean que se refiere a la visibilidad del spinner
     */
    public void setSpinnerVisible(boolean visible) {
        porcentajeSpinner.setEnabled(visible);
    }

    /**
     * Funcion que limpia y reinicia todos los campos.
     * Los campos de texto los deja vacios y el resto de elementos los pone a su valor por defecto
     */
    public void limpiarCampos(){
        anadirNombreTareaTextField.setText("");
        descripcionTextArea.setText("");
        fechaDateChooser.setDate(java.sql.Date.valueOf(java.time.LocalDate.now()));
        prioridadComboBox.setSelectedIndex(0);
        porcentajeSpinner.setValue(0);
        completadoCheckBox.setSelected(false);
        listaTareasList.clearSelection();
        verNombreTareaLabel.setText("");
        verDescripcionTextArea.setText("");
        verFechaModificableLabel.setText("");
        verPrioridadModificableLabel.setText("");
        verProgresoProgressBar.setValue(0);
        verProgresoNumeroNoModificableLabel.setText("");
        porcentajeSpinner.setEnabled(true);
        erroresLabel.setText("");
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton GestorListasButton;
    private javax.swing.JButton MenuButton;
    private javax.swing.JLabel anadirNombreTareaLabel;
    private javax.swing.JTextField anadirNombreTareaTextField;
    private javax.swing.JLabel anadirProgresoLabel;
    private javax.swing.JCheckBox completadoCheckBox;
    private javax.swing.JLabel descripcionLabel;
    private javax.swing.JScrollPane descripcionScrollPane;
    private javax.swing.JTextArea descripcionTextArea;
    private javax.swing.JButton editarButton;
    private javax.swing.JButton eliminarButton;
    private javax.swing.JLabel erroresLabel;
    private com.toedter.calendar.JDateChooser fechaDateChooser;
    private javax.swing.JLabel fechaLabel;
    private javax.swing.JButton guardarButton;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel10;
    private javax.swing.JPanel jPanel11;
    private javax.swing.JPanel jPanel12;
    private javax.swing.JPanel jPanel13;
    private javax.swing.JPanel jPanel14;
    private javax.swing.JPanel jPanel15;
    private javax.swing.JPanel jPanel16;
    private javax.swing.JPanel jPanel17;
    private javax.swing.JPanel jPanel18;
    private javax.swing.JPanel jPanel19;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel20;
    private javax.swing.JPanel jPanel21;
    private javax.swing.JPanel jPanel22;
    private javax.swing.JPanel jPanel23;
    private javax.swing.JPanel jPanel24;
    private javax.swing.JPanel jPanel25;
    private javax.swing.JPanel jPanel26;
    private javax.swing.JPanel jPanel27;
    private javax.swing.JPanel jPanel28;
    private javax.swing.JPanel jPanel29;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel30;
    private javax.swing.JPanel jPanel31;
    private javax.swing.JPanel jPanel32;
    private javax.swing.JPanel jPanel35;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JPanel jPanel9;
    private javax.swing.JButton limpiarButton;
    private javax.swing.JLabel listaActualLabel;
    private javax.swing.JList<String> listaTareasList;
    private javax.swing.JScrollPane listaTareasScrollPane;
    private javax.swing.JSpinner porcentajeSpinner;
    private javax.swing.JComboBox<String> prioridadComboBox;
    private javax.swing.JLabel prioridadLabel;
    private javax.swing.JComboBox<String> seleccionarListaComboBox;
    private javax.swing.JScrollPane verDescripcionJSCroll;
    private javax.swing.JLabel verDescripcionNoModificableLabel;
    private javax.swing.JTextArea verDescripcionTextArea;
    private javax.swing.JLabel verFechaModificableLabel;
    private javax.swing.JLabel verFechaNoModificableLabel;
    private javax.swing.JLabel verNombreTareaLabel;
    private javax.swing.JLabel verNombreTareaNoModificableLabel;
    private javax.swing.JLabel verPrioridadModificableLabel;
    private javax.swing.JLabel verPrioridadNoModificableLabel;
    private javax.swing.JLabel verProgresoLabel;
    private javax.swing.JLabel verProgresoNumeroNoModificableLabel;
    private javax.swing.JProgressBar verProgresoProgressBar;
    // End of variables declaration//GEN-END:variables
}
