/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package uva.ipc.practica2.vista;

import java.util.ArrayList;
import uva.ipc.practica2.modelo.ListaTareas;
import uva.ipc.practica2.modelo.Tarea;


/**
 *
 * @author tomip
 */
public class VistaGestorListas extends javax.swing.JFrame {
    
    private ControladorGestorListas controlador;

    /**
     * Creates new form VistaGestorListas
     */
    public VistaGestorListas() {
        initComponents();
        this.controlador = new ControladorGestorListas(this);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        jPanel2 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        jPanel5 = new javax.swing.JPanel();
        listasLabel = new javax.swing.JLabel();
        listaListasScrollPane = new javax.swing.JScrollPane();
        listaListasList = new javax.swing.JList<>();
        jPanel6 = new javax.swing.JPanel();
        jPanel15 = new javax.swing.JPanel();
        anadirListaLabel = new javax.swing.JLabel();
        anadirListaTextField = new javax.swing.JTextField();
        jPanel16 = new javax.swing.JPanel();
        anadirListaButton = new javax.swing.JButton();
        borrarListaButton = new javax.swing.JButton();
        jPanel4 = new javax.swing.JPanel();
        jPanel7 = new javax.swing.JPanel();
        verNombreListaLabel = new javax.swing.JLabel();
        verNombreListaTextField = new javax.swing.JTextField();
        jPanel8 = new javax.swing.JPanel();
        tareasCompletadasLabel = new javax.swing.JLabel();
        jPanel9 = new javax.swing.JPanel();
        tareasCompletadasScrollPane = new javax.swing.JScrollPane();
        listaTareasCompletadasList = new javax.swing.JList<>();
        jPanel10 = new javax.swing.JPanel();
        tareasPendientesLabel = new javax.swing.JLabel();
        jPanel11 = new javax.swing.JPanel();
        tareasPendientesScrollPane = new javax.swing.JScrollPane();
        listaTareasPendientesList = new javax.swing.JList<>();
        jPanel12 = new javax.swing.JPanel();
        verNumTareasCompletadasLabel = new javax.swing.JLabel();
        verNumTareasCompletadasTextField = new javax.swing.JTextField();
        jPanel13 = new javax.swing.JPanel();
        completarTareaButton = new javax.swing.JButton();
        jPanel14 = new javax.swing.JPanel();
        errorLabel = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        irMenuButton = new javax.swing.JButton();
        irTareasButton = new javax.swing.JButton();
        jPanel17 = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(800, 700));
        setPreferredSize(new java.awt.Dimension(1000, 600));
        getContentPane().setLayout(new java.awt.GridBagLayout());

        jPanel2.setLayout(new java.awt.GridBagLayout());

        jPanel3.setLayout(new java.awt.GridBagLayout());

        jPanel5.setLayout(new java.awt.BorderLayout());

        listasLabel.setText("Listas creadas:");
        jPanel5.add(listasLabel, java.awt.BorderLayout.PAGE_START);

        listaListasList.addListSelectionListener(new javax.swing.event.ListSelectionListener() {
            public void valueChanged(javax.swing.event.ListSelectionEvent evt) {
                listaListasListValueChanged(evt);
            }
        });
        listaListasScrollPane.setViewportView(listaListasList);

        jPanel5.add(listaListasScrollPane, java.awt.BorderLayout.CENTER);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.weighty = 0.7;
        jPanel3.add(jPanel5, gridBagConstraints);

        jPanel6.setLayout(new java.awt.GridBagLayout());

        jPanel15.setLayout(new java.awt.BorderLayout());

        anadirListaLabel.setText("Nombre de la nueva lista: ");
        jPanel15.add(anadirListaLabel, java.awt.BorderLayout.CENTER);
        jPanel15.add(anadirListaTextField, java.awt.BorderLayout.PAGE_END);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.weighty = 0.7;
        jPanel6.add(jPanel15, gridBagConstraints);

        jPanel16.setLayout(new java.awt.GridBagLayout());

        anadirListaButton.setText("Añadir Lista");
        anadirListaButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                anadirListaButtonActionPerformed(evt);
            }
        });
        jPanel16.add(anadirListaButton, new java.awt.GridBagConstraints());

        borrarListaButton.setText("Borrar Lista");
        borrarListaButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                borrarListaButtonActionPerformed(evt);
            }
        });
        jPanel16.add(borrarListaButton, new java.awt.GridBagConstraints());

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.weightx = 0.3;
        gridBagConstraints.weighty = 1.0;
        jPanel6.add(jPanel16, gridBagConstraints);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.weighty = 0.3;
        jPanel3.add(jPanel6, gridBagConstraints);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.weightx = 0.3;
        gridBagConstraints.weighty = 1.0;
        gridBagConstraints.insets = new java.awt.Insets(10, 10, 10, 10);
        jPanel2.add(jPanel3, gridBagConstraints);

        jPanel4.setLayout(new java.awt.GridBagLayout());

        jPanel7.setLayout(new java.awt.GridBagLayout());

        verNombreListaLabel.setText("Lista:");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.weightx = 0.05;
        gridBagConstraints.weighty = 1.0;
        jPanel7.add(verNombreListaLabel, gridBagConstraints);

        verNombreListaTextField.setEditable(false);
        verNombreListaTextField.setMaximumSize(new java.awt.Dimension(2147483647, 26));
        verNombreListaTextField.setMinimumSize(new java.awt.Dimension(64, 26));
        verNombreListaTextField.setPreferredSize(new java.awt.Dimension(374, 26));
        verNombreListaTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                verNombreListaTextFieldActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.weightx = 0.95;
        gridBagConstraints.weighty = 1.0;
        jPanel7.add(verNombreListaTextField, gridBagConstraints);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.weighty = 0.1;
        jPanel4.add(jPanel7, gridBagConstraints);

        jPanel8.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.LEFT));

        tareasCompletadasLabel.setText("Tareas completadas:");
        jPanel8.add(tareasCompletadasLabel);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.weighty = 0.1;
        jPanel4.add(jPanel8, gridBagConstraints);

        jPanel9.setLayout(new java.awt.BorderLayout());

        tareasCompletadasScrollPane.setMinimumSize(new java.awt.Dimension(320, 22));
        tareasCompletadasScrollPane.setPreferredSize(new java.awt.Dimension(320, 134));

        tareasCompletadasScrollPane.setViewportView(listaTareasCompletadasList);

        jPanel9.add(tareasCompletadasScrollPane, java.awt.BorderLayout.CENTER);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 3;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.weighty = 0.2;
        jPanel4.add(jPanel9, gridBagConstraints);

        jPanel10.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.LEFT));

        tareasPendientesLabel.setText("Tareas pendientes");
        jPanel10.add(tareasPendientesLabel);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 4;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.weighty = 0.1;
        jPanel4.add(jPanel10, gridBagConstraints);

        jPanel11.setLayout(new java.awt.BorderLayout());

        tareasPendientesScrollPane.setMinimumSize(new java.awt.Dimension(320, 22));
        tareasPendientesScrollPane.setPreferredSize(new java.awt.Dimension(320, 150));

        listaTareasPendientesList.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { " " };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        tareasPendientesScrollPane.setViewportView(listaTareasPendientesList);

        jPanel11.add(tareasPendientesScrollPane, java.awt.BorderLayout.CENTER);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 5;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.weighty = 0.2;
        jPanel4.add(jPanel11, gridBagConstraints);

        verNumTareasCompletadasLabel.setText("Tareas Completadas");
        jPanel12.add(verNumTareasCompletadasLabel);

        verNumTareasCompletadasTextField.setEditable(false);
        verNumTareasCompletadasTextField.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        verNumTareasCompletadasTextField.setText("0");
        verNumTareasCompletadasTextField.setMinimumSize(new java.awt.Dimension(100, 26));
        verNumTareasCompletadasTextField.setPreferredSize(new java.awt.Dimension(30, 26));
        verNumTareasCompletadasTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                verNumTareasCompletadasTextFieldActionPerformed(evt);
            }
        });
        jPanel12.add(verNumTareasCompletadasTextField);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 6;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.weighty = 0.1;
        jPanel4.add(jPanel12, gridBagConstraints);

        completarTareaButton.setText("Completar Tarea");
        completarTareaButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                completarTareaButtonActionPerformed(evt);
            }
        });
        jPanel13.add(completarTareaButton);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 7;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.weighty = 0.1;
        jPanel4.add(jPanel13, gridBagConstraints);

        errorLabel.setForeground(new java.awt.Color(255, 0, 0));
        jPanel14.add(errorLabel);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 8;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.weighty = 0.1;
        jPanel4.add(jPanel14, gridBagConstraints);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.weightx = 0.7;
        gridBagConstraints.weighty = 1.0;
        gridBagConstraints.insets = new java.awt.Insets(10, 10, 10, 10);
        jPanel2.add(jPanel4, gridBagConstraints);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.weighty = 0.95;
        gridBagConstraints.insets = new java.awt.Insets(10, 10, 10, 10);
        getContentPane().add(jPanel2, gridBagConstraints);

        jPanel1.setMaximumSize(new java.awt.Dimension(116, 33));
        jPanel1.setMinimumSize(new java.awt.Dimension(116, 33));
        jPanel1.setPreferredSize(new java.awt.Dimension(116, 33));
        jPanel1.setLayout(new java.awt.GridBagLayout());

        irMenuButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/uva/ipc/practica2/vista/flecha_atras.png"))); // NOI18N
        irMenuButton.setText("Menú Principal");
        irMenuButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                irMenuButtonActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.weightx = 0.25;
        gridBagConstraints.weighty = 1.0;
        jPanel1.add(irMenuButton, gridBagConstraints);

        irTareasButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/uva/ipc/practica2/vista/editar_tareas.png"))); // NOI18N
        irTareasButton.setText("Gestionar Tareas");
        irTareasButton.setMaximumSize(new java.awt.Dimension(150, 41));
        irTareasButton.setMinimumSize(new java.awt.Dimension(150, 41));
        irTareasButton.setPreferredSize(new java.awt.Dimension(150, 41));
        irTareasButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                irTareasButtonActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 3;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.weightx = 0.25;
        gridBagConstraints.weighty = 1.0;
        jPanel1.add(irTareasButton, gridBagConstraints);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.weightx = 0.5;
        gridBagConstraints.weighty = 1.0;
        jPanel1.add(jPanel17, gridBagConstraints);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.weighty = 0.05;
        gridBagConstraints.insets = new java.awt.Insets(10, 10, 10, 10);
        getContentPane().add(jPanel1, gridBagConstraints);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void verNombreListaTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_verNombreListaTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_verNombreListaTextFieldActionPerformed

    private void irTareasButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_irTareasButtonActionPerformed
        // TODO add your handling code here:
        controlador.procesarEventoVistaTareas();
    }//GEN-LAST:event_irTareasButtonActionPerformed

    private void irMenuButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_irMenuButtonActionPerformed
        // TODO add your handling code here:
        controlador.procesarEventoVistaMenu();
    }//GEN-LAST:event_irMenuButtonActionPerformed

    private void verNumTareasCompletadasTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_verNumTareasCompletadasTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_verNumTareasCompletadasTextFieldActionPerformed

    private void anadirListaButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_anadirListaButtonActionPerformed
        // TODO add your handling code here:
        controlador.procesarEventoGuardar();
    }//GEN-LAST:event_anadirListaButtonActionPerformed

    private void listaListasListValueChanged(javax.swing.event.ListSelectionEvent evt) {//GEN-FIRST:event_listaListasListValueChanged
        // TODO add your handling code here:
        controlador.procesarEventoSeleccionarLista();
    }//GEN-LAST:event_listaListasListValueChanged

    private void completarTareaButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_completarTareaButtonActionPerformed
        // TODO add your handling code here:
        controlador.procesarCompletarTarea();
    }//GEN-LAST:event_completarTareaButtonActionPerformed

    private void borrarListaButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_borrarListaButtonActionPerformed
        // TODO add your handling code here:
        controlador.procesarEventoBorrar();
    }//GEN-LAST:event_borrarListaButtonActionPerformed

    
    public void actualizarListas(ArrayList<ListaTareas> listas) {
        String[] listasArray = new String[listas.size()];
    
        for (int i = 0; i < listas.size(); i++) {
            listasArray[i] = listas.get(i).getNombre();
        }
        listaListasList.setListData(listasArray);
    }
    
    public String getNombreNuevaLista(){
        return anadirListaTextField.getText();
    }
    
    public int getPosicionSelectPendiente(){
        return listaTareasPendientesList.getSelectedIndex();
    }
    
    public void cambiarCamposListaSeleccionada(ListaTareas listaSeleccionada) {
        verNombreListaTextField.setText(listaSeleccionada.getNombre());
        ArrayList <Tarea> listas=listaSeleccionada.getTareas();
        int comp=listaSeleccionada.getNumeroTareasCompletadas();
        String[] listaComp=new String[comp];
        String[] listaPend=new String[listas.size()-comp];
        comp=0;
        for (int i = 0; i < listas.size(); i++) {
            Tarea t=listas.get(i);
            if(t.getProgreso()==100){
                listaComp[comp]=listas.get(i).toString();
                comp++;
            }else{
                listaPend[i-comp]=listas.get(i).stringPendiente();
            }
        }
        listaTareasCompletadasList.setListData(listaComp);
        listaTareasPendientesList.setListData(listaPend);
        verNumTareasCompletadasTextField.setText(Integer.toString(comp));
    }
    
    public int getIndexListaSeleccionada(){
            return(listaListasList.getSelectedIndex());
    }
    
    public void setError(String s){
        errorLabel.setText(s);
    }
    
    public void vaciarCampos(){
        listaListasList.clearSelection();
        verNombreListaTextField.setText("");
        listaTareasCompletadasList.setListData(new String[0]);
        listaTareasPendientesList.setListData(new String[0]);
        anadirListaTextField.setText("");
        errorLabel.setText("");
    }
    
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton anadirListaButton;
    private javax.swing.JLabel anadirListaLabel;
    private javax.swing.JTextField anadirListaTextField;
    private javax.swing.JButton borrarListaButton;
    private javax.swing.JButton completarTareaButton;
    private javax.swing.JLabel errorLabel;
    private javax.swing.JButton irMenuButton;
    private javax.swing.JButton irTareasButton;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel10;
    private javax.swing.JPanel jPanel11;
    private javax.swing.JPanel jPanel12;
    private javax.swing.JPanel jPanel13;
    private javax.swing.JPanel jPanel14;
    private javax.swing.JPanel jPanel15;
    private javax.swing.JPanel jPanel16;
    private javax.swing.JPanel jPanel17;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JPanel jPanel9;
    private javax.swing.JList<String> listaListasList;
    private javax.swing.JScrollPane listaListasScrollPane;
    private javax.swing.JList<String> listaTareasCompletadasList;
    private javax.swing.JList<String> listaTareasPendientesList;
    private javax.swing.JLabel listasLabel;
    private javax.swing.JLabel tareasCompletadasLabel;
    private javax.swing.JScrollPane tareasCompletadasScrollPane;
    private javax.swing.JLabel tareasPendientesLabel;
    private javax.swing.JScrollPane tareasPendientesScrollPane;
    private javax.swing.JLabel verNombreListaLabel;
    private javax.swing.JTextField verNombreListaTextField;
    private javax.swing.JLabel verNumTareasCompletadasLabel;
    private javax.swing.JTextField verNumTareasCompletadasTextField;
    // End of variables declaration//GEN-END:variables

    
}
